import {_electron as electron,type ElectronApplication} from 'playwright-core';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../src/store.ts';
import type {PublicState} from '../src/shared.ts';
const data=await mkdtemp(join(tmpdir(),'loom-stream-ui-')),log=join(data,'wire.jsonl'),bin=join(data,'runtime/node_modules/@openai/codex/bin');await mkdir(bin,{recursive:true});await writeFile(join(data,'runtime/.ready'),'fixture');
const opening='<h2>An early explanation</h2><p>Read this while the rest is built. The space is $\\mathbb{R}^2$.</p><svg viewBox="0 0 400 60" role="img" aria-label="A useful first figure"><path d="M10 30H390" stroke="currentColor"/><text x="20" y="25">Input → intermediate step → result</text></svg><button id="count">Count: 0</button><script>window.__partialRan=true;';
const closing='document.querySelector("#count").onclick=()=>{document.querySelector("#count").textContent="Count: 1"};</script>';
await writeFile(join(bin,'codex.js'),`const fs=require('node:fs'),rl=require('node:readline');let id;const out=p=>process.stdout.write(JSON.stringify(p)+'\\n');rl.createInterface({input:process.stdin}).on('line',line=>{const p=JSON.parse(line);if(!p.method){if(p.id===800){id=JSON.parse(p.result.contentItems[0].text).id;setTimeout(()=>out({id:801,method:'item/tool/call',params:{threadId:'thread',tool:'stream_canvas',arguments:{id,html:${JSON.stringify(closing)},complete:true}}}),3000);}if(p.id===801)out({method:'turn/completed',params:{threadId:'thread',turn:{id:'turn',status:'completed'}}});return;}if(p.method==='initialized')return;let result={};if(p.method==='account/read')result={account:{type:'chatgpt'}};if(p.method==='model/list')result={data:[{id:'fixture',model:'fixture',displayName:'Fixture',supportedReasoningEfforts:[{reasoningEffort:'low'}]}],nextCursor:null};if(p.method==='thread/start')result={thread:{id:'thread'}};if(p.method==='turn/start'){result={turn:{id:'turn'}};fs.appendFileSync(${JSON.stringify(log)},JSON.stringify({at:Date.now()})+'\\n');setTimeout(()=>out({id:800,method:'item/tool/call',params:{threadId:'thread',tool:'stream_canvas',arguments:{title:'Streamed lesson',html:${JSON.stringify(opening)}}}}),100);}out({id:p.id,result});});`);
const store=new Store(data);await store.init();await store.newChat({provider:'openai-codex',model:'fixture'});await store.commit();let app:ElectronApplication|undefined;const errors:string[]=[],checks:string[]=[],metrics:any={};
try{const env=Object.fromEntries(Object.entries({...process.env,STUDIO_DATA_DIR:data}).filter((e):e is [string,string]=>typeof e[1]==='string'&&e[0]!=='ELECTRON_RUN_AS_NODE'));app=await electron.launch({executablePath:resolve('node_modules/electron/dist/electron'),args:['.','--no-sandbox','--ozone-platform=x11'],env});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.locator('.app').waitFor();await page.evaluate(()=>window.studio.call('refreshAccounts'));await page.getByRole('textbox',{name:'Message',exact:true}).fill('Build a small explanation');await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await page.locator('.building-canvas').waitFor();const preview=page.frameLocator('iframe[title="Streamed lesson preview"]');await preview.getByRole('heading',{name:'An early explanation'}).waitFor();metrics.firstPreviewMs=Date.now()-JSON.parse((await readFile(log,'utf8')).trim().split('\n')[0]).at;assert(metrics.firstPreviewMs<1800);assert.equal(await preview.locator('.katex').count(),1);assert.equal(await page.evaluate(()=>window.studio.call<PublicState>('state')).then(s=>s.canvases.length),0);const frame=page.frames().find(f=>f.url().startsWith('studio://preview'));assert(frame);assert.equal(await frame.evaluate(()=>(window as any).__partialRan),undefined);assert(await preview.locator('#loom-preview-content').getAttribute('inert')!==null);checks.push('Explanation, typeset math and a figure are readable before publication; incomplete scripts never run');
  const typing=await page.evaluate(async()=>{const input=document.querySelector('textarea')!,set=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')!.set!;const delays=[];for(let i=0;i<15;i++){const start=performance.now();set.call(input,'Next thought '+i);input.dispatchEvent(new Event('input',{bubbles:true}));await new Promise<void>(r=>requestAnimationFrame(()=>r()));delays.push(performance.now()-start);}return delays.sort((a,b)=>a-b);});metrics.typingP95Ms=typing[Math.floor(typing.length*.95)];assert(metrics.typingP95Ms<100);
  await page.frameLocator('iframe[title="Streamed lesson"]').getByRole('button',{name:'Count: 0',exact:true}).waitFor();await page.frameLocator('iframe[title="Streamed lesson"]').getByRole('button',{name:'Count: 0',exact:true}).click();await page.frameLocator('iframe[title="Streamed lesson"]').getByRole('button',{name:'Count: 1',exact:true}).waitFor();assert.equal(await page.locator('.building-canvas').count(),0);assert.match(await page.getByRole('textbox',{name:'Message',exact:true}).inputValue(),/Next thought/);checks.push('Validated final code replaces the preview, runs real interactions, and retains the next draft');
  assert.deepEqual(errors,[]);await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/canvas-stream.png'});await writeFile('test-results/canvas-stream-report.json',JSON.stringify({checks,metrics,errors,fixture:'Deterministic protocol; rendering overhead rather than network/model latency'},null,2));console.log(JSON.stringify({checks,metrics,errors}));
}finally{await app?.close();await rm(data,{recursive:true,force:true});}
