import {_electron as electron,type ElectronApplication,type Page} from 'playwright-core';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve,delimiter} from 'node:path';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
import type {PublicState} from '../src/shared.ts';import {pdfFixture} from './fixtures.ts';
const root=await mkdtemp(join(tmpdir(),'loom-clipboard-')),data=join(root,'data'),bin=join(root,'bin'),log=join(root,'wire.jsonl'),pdfPath=join(root,'Copied paper.pdf');await mkdir(bin);await mkdir('test-results',{recursive:true});await writeFile(pdfPath,pdfFixture());
await writeFile(join(bin,'claude'),`#!/usr/bin/env node
const fs=require('node:fs'),rl=require('node:readline');rl.createInterface({input:process.stdin}).on('line',line=>{fs.appendFileSync(${JSON.stringify(log)},line+'\\n');const out=x=>process.stdout.write(JSON.stringify(x)+'\\n');out({type:'stream_event',event:{delta:{type:'text_delta',text:'Attachment received.'}}});out({type:'result',session_id:'fixture',is_error:false});});`,{mode:0o755});
let app:ElectronApplication|undefined,page!:Page;let savedClipboard:any,clipboardBackup:any;const errors:string[]=[],report:any[]=[];
const sha=(value:Uint8Array)=>createHash('sha256').update(value).digest('hex');
async function until(test:()=>Promise<boolean>){const end=Date.now()+15000;while(!await test()){assert(Date.now()<end,'Clipboard operation timed out');await new Promise(r=>setTimeout(r,35));}}
async function launch(){const env:NodeJS.ProcessEnv={...process.env,STUDIO_DATA_DIR:data,PATH:bin+delimiter+process.env.PATH};delete env.ELECTRON_RUN_AS_NODE;app=await electron.launch({executablePath:resolve('node_modules/electron/dist/electron'),args:['.','--no-sandbox','--ozone-platform=x11'],env:Object.fromEntries(Object.entries(env).filter((x):x is [string,string]=>typeof x[1]==='string'))});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.locator('.app').waitFor();}
const state=()=>page.evaluate(()=>window.studio.call<PublicState>('state'));
async function finish(chatId:string){await until(async()=>{const s=await state();return !!s.runs.find(r=>r.chatId===chatId)&&!s.runs.find(r=>r.chatId===chatId)?.busy&&s.chats.find(c=>c.id===chatId)!.messages.some(m=>m.role==='assistant'&&m.text==='Attachment received.');});assert.equal((await state()).runs.find(r=>r.chatId===chatId)?.error,undefined);}
try{
 await launch();savedClipboard=await app!.evaluate(async({clipboard})=>{(globalThis as any).__loomClipboard=await clipboard.read();return true;});
 // Test 1: a real screenshot is put on the OS clipboard, then pasted by Ctrl+V.
 const screenshot=await page.screenshot();await app!.evaluate(async({clipboard,ClipboardItem},bytes)=>{await clipboard.write([new ClipboardItem({'image/png':new Blob([Uint8Array.from(bytes)],{type:'image/png'})})]);},[...screenshot]);const screenshotId=(await state()).activeChatId!;
 await page.getByRole('combobox',{name:'Chat provider'}).selectOption('claude-code');const start=Date.now();await page.getByRole('textbox',{name:'Message',exact:true}).focus();await page.keyboard.press('Control+V');await page.locator('.composer .attachment img').waitFor();const screenshotPreviewMs=Date.now()-start;
 const image=(await state()).attachments.find(a=>a.chatId===screenshotId)!;assert.equal(image.mime,'image/png');assert.equal((await state()).chats.find(c=>c.id===screenshotId)!.draftAttachments.length,1);
 const pixels=await app!.evaluate(({nativeImage},bytes)=>{const a=nativeImage.createFromBuffer(Buffer.from(bytes));let hash=2166136261;for(const byte of a.toBitmap())hash=Math.imul(hash^byte,16777619);return{width:a.getSize().width,height:a.getSize().height,hash:hash>>>0};},[...screenshot]);const storedPixels=await app!.evaluate(({nativeImage},path)=>{const a=nativeImage.createFromPath(path);let hash=2166136261;for(const byte of a.toBitmap())hash=Math.imul(hash^byte,16777619);return{width:a.getSize().width,height:a.getSize().height,hash:hash>>>0};},image.path);assert.equal(storedPixels.hash,pixels.hash);assert.equal(storedPixels.width,pixels.width);
 await page.locator('.composer .attachment img').click();await page.locator('.attachment-preview img').waitFor();await page.screenshot({path:'test-results/clipboard-screenshot-preview.png'});await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('textbox',{name:'Message',exact:true}).fill('Inspect my screenshot');await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await finish(screenshotId);await until(async()=>(await state()).chats.find(c=>c.id===screenshotId)!.messages.some(m=>m.role==='user'&&m.attachments?.includes(image.id)));
 let wire=(await readFile(log,'utf8')).trim().split('\n').map(x=>JSON.parse(x));assert(wire[0].message.content.some((c:any)=>c.type==='image'&&c.source.media_type==='image/png'&&c.source.data.length>100));assert.equal((await state()).chats.find(c=>c.id===screenshotId)!.draftAttachments.length,0);
 // Move the clipboard backup into the test process across the controlled restart.
 const backup=clipboardBackup=await app!.evaluate(async()=>{const items=(globalThis as any).__loomClipboard;return await Promise.all(items.map(async(item:any)=>({types:await Promise.all(item.types.map(async(type:string)=>{const value=await item.getType(type);return{type,bytes:value instanceof Blob?[...new Uint8Array(await value.arrayBuffer())]:undefined,value:value instanceof Blob?undefined:value};}))})));});
 await app!.close();await launch();await page.locator('.message .attachment img').waitFor();assert((await state()).chats.find(c=>c.id===screenshotId)!.messages.some(m=>m.attachments?.includes(image.id)));report.push({test:'Screenshot Ctrl+V',previewMs:screenshotPreviewMs,pixelsPreserved:true,preview:true,sentAsImage:true,persisted:true});console.log('PASS Screenshot Ctrl+V, preview, send and restart');
 // Test 2 starts only after the complete screenshot test has passed.
 await page.getByRole('button',{name:'New chat',exact:true}).click();await until(async()=>(await state()).activeChatId!==screenshotId);const pdfId=(await state()).activeChatId!;await app!.evaluate(async({clipboard,ClipboardItem},uri)=>{await clipboard.write([new ClipboardItem({'electron application/osclipboard;format="text/uri-list"':new Blob([uri+'\r\n'],{type:'text/uri-list'})})]);},pathToFileURL(pdfPath).href);
 const pdfStart=Date.now();await page.getByRole('textbox',{name:'Message',exact:true}).focus();await page.keyboard.press('Control+V');await page.locator('.composer .attachment').getByText('Copied paper.pdf',{exact:true}).waitFor();const pdfPreviewMs=Date.now()-pdfStart;const pdf=(await state()).attachments.find(a=>a.chatId===pdfId)!;assert.equal(pdf.mime,'application/pdf');assert.equal(sha(await readFile(pdf.path)),sha(await readFile(pdfPath)));await page.locator('.composer .attachment-open').click();await page.locator('.pdf-page img').waitFor();await page.getByRole('button',{name:'Next PDF page'}).click();await page.locator('.pdf-page img').waitFor();assert.equal(await page.getByRole('spinbutton',{name:'PDF page'}).inputValue(),'2');await page.getByRole('combobox',{name:'PDF view'}).selectOption('text');await page.getByText('Amplitude is maximum displacement.',{exact:false}).waitFor();await page.screenshot({path:'test-results/clipboard-pdf-preview.png'});await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('textbox',{name:'Message',exact:true}).fill('Read my pasted PDF');await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await finish(pdfId);wire=(await readFile(log,'utf8')).trim().split('\n').map(x=>JSON.parse(x));assert(wire.at(-1).message.content.some((c:any)=>c.type==='text'&&c.text.includes('PDF first page')&&c.text.includes('Copied paper.pdf')));assert((await state()).chats.find(c=>c.id===pdfId)!.messages.some(m=>m.attachments?.includes(pdf.id)));await app!.close();await launch();await page.locator('.message .attachment-open').getByText('Copied paper.pdf',{exact:true}).waitFor();report.push({test:'PDF Ctrl+V',previewMs:pdfPreviewMs,bytesPreserved:true,pagePreview:true,textPreview:true,sentWithSourceContext:true,persisted:true});console.log('PASS PDF Ctrl+V, pages, text, send and restart');
 await app!.evaluate(async({clipboard,ClipboardItem},items)=>{await clipboard.write(items.map((item:any)=>new ClipboardItem(Object.fromEntries(item.types.map((t:any)=>[t.type,t.bytes?new Blob([Uint8Array.from(t.bytes)]):t.value])))));},backup);savedClipboard=false;assert.deepEqual(errors,[]);await writeFile('test-results/clipboard-report.json',JSON.stringify({report,errors,platform:process.platform},null,2));
}finally{if(savedClipboard&&app&&clipboardBackup)await app.evaluate(async({clipboard,ClipboardItem},items)=>{await clipboard.write(items.map((item:any)=>new ClipboardItem(Object.fromEntries(item.types.map((t:any)=>[t.type,t.bytes?new Blob([Uint8Array.from(t.bytes)]):t.value])))));},clipboardBackup).catch(()=>{});else if(savedClipboard&&app)await app.evaluate(async({clipboard})=>{const saved=(globalThis as any).__loomClipboard;if(saved)await clipboard.write(saved);}).catch(()=>{});await app?.close();await rm(root,{recursive:true,force:true});}
