import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { join, delimiter } from 'node:path';
import { tmpdir } from 'node:os';
import { CodexRun, findCodex } from '../src/codex.ts';
import type { Chat } from '../src/shared.ts';
test('updated private Codex runtime carries Sol Ultrafast, scoped tools, images, steering, and cancellation',async()=>{
  const root=await mkdtemp(join(tmpdir(),'loom-codex-')),bin=join(root,'bin'),log=join(root,'messages.jsonl'),oldPath=process.env.PATH;await mkdir(bin);
  await writeFile(join(bin,'codex'),`#!/usr/bin/env node
const fs=require('node:fs'),rl=require('node:readline').createInterface({input:process.stdin});let stopped=false;const out=p=>process.stdout.write(JSON.stringify(p)+'\\n');rl.on('line',line=>{const p=JSON.parse(line);fs.appendFileSync(${JSON.stringify(log)},line+'\\n');if(!p.method){if(p.id===700){out({method:'item/agentMessage/delta',params:{delta:'Canvas ready.'}});setTimeout(()=>{if(!stopped)out({method:'turn/completed',params:{turn:{id:'turn',status:'completed'}}})},600);}return;}if(p.method==='initialized')return;let result={};if(p.method==='thread/start')result={thread:{id:'thread'}};if(p.method==='turn/start')result={turn:{id:'turn'}};out({id:p.id,result});if(p.method==='turn/start'){out({method:'turn/started',params:{turn:{id:'turn'}}});out({id:700,method:'item/tool/call',params:{tool:'publish_canvas',arguments:{title:'Sol canvas',html:'<button>Working</button>'}}});}if(p.method==='turn/interrupt'){stopped=true;out({method:'turn/completed',params:{turn:{id:'turn',status:'interrupted'}}});}});
`,{mode:0o755});process.env.PATH=bin+delimiter+oldPath;
  const home=join(root,'codex'),runtime=join(root,'runtime'),entry=join(runtime,'node_modules','@openai','codex','bin','codex.js');await mkdir(join(runtime,'node_modules','@openai','codex','bin'),{recursive:true});await writeFile(entry,await readFile(join(bin,'codex')));assert.equal(await findCodex(home),join(bin,'codex'));await writeFile(join(runtime,'.ready'),'fixture\n');assert.equal(await findCodex(home),entry);
  let called:any,text='',run:CodexRun|undefined;const chat:Chat={id:'chat',title:'Test',provider:'openai-codex',model:'gpt-6.1-sol',speed:'ultrafast',thinking:'low',messages:[],draft:'',draftAttachments:[],updatedAt:0};const options={home,cwd:root,chat,systemPrompt:'Use creative canvases.',tools:[{name:'publish_canvas',description:'Publish',parameters:{type:'object',properties:{title:{type:'string'},html:{type:'string'}},required:['title','html']}}],execute:async(name:string,args:any)=>{called={name,args};return{content:[{type:'text',text:'Saved'}]};},delta:(t:string)=>{text+=t;},activity:()=>{}};
  try{run=new CodexRun(options);const complete=run.prompt('Teach me',[{mimeType:'image/png',data:'aW1hZ2U='}]);await run.steer('Keep page citations.');let start=Date.now();while(!called){if(Date.now()-start>5000)throw Error('No tool call');await new Promise(r=>setTimeout(r,15));}await run.steer('Add a quiz');await complete;run.close();assert.equal(text,'Canvas ready.');assert.equal(called.name,'publish_canvas');let packets=(await readFile(log,'utf8')).trim().split('\n').map(l=>JSON.parse(l));const thread=packets.find(p=>p.method==='thread/start').params;assert.equal(thread.model,'gpt-6.1-sol');assert.equal(thread.serviceTier,'ultrafast');assert.equal(thread.sandbox,'read-only');assert.equal(thread.dynamicTools[0].type,'function');assert.equal(thread.config.web_search,'live');assert.equal(thread.config['features.shell_tool'],false);const prompt=packets.find(p=>p.method==='turn/start').params;assert.equal(prompt.effort,'low');assert(prompt.input[0].text.includes('Keep page citations.'));assert.equal(prompt.input[1].type,'image');assert.equal(packets.find(p=>p.method==='turn/steer').params.expectedTurnId,'turn');assert.equal(packets.find(p=>p.id===700&&!p.method).result.success,true);
    called=undefined;run=new CodexRun(options);const interrupted=run.prompt('Another run');const deadline=Date.now()+5000;while(!called){if(Date.now()>deadline)throw Error('Second turn did not start');await new Promise(r=>setTimeout(r,15));}await run.stop();await interrupted;packets=(await readFile(log,'utf8')).trim().split('\n').map(l=>JSON.parse(l));assert(packets.some(p=>p.method==='turn/interrupt'));
  }finally{run?.close();process.env.PATH=oldPath;await rm(root,{recursive:true,force:true});}
});

test('one Codex connection isolates concurrent chats, reuses context, and recovers after runtime exit',async()=>{
 const {CodexClient}=await import('../src/codex.ts');
 const root=await mkdtemp(join(tmpdir(),'loom-pool-')),home=join(root,'codex'),runtime=join(root,'runtime'),entry=join(runtime,'node_modules','@openai','codex','bin','codex.js'),log=join(root,'wire.jsonl');
 await mkdir(join(runtime,'node_modules','@openai','codex','bin'),{recursive:true});await writeFile(join(runtime,'.ready'),'fixture');
 await writeFile(entry,`const fs=require('node:fs'),rl=require('node:readline');let sequence=0,toolId=100;const turns=new Map(),calls=new Map();const out=p=>process.stdout.write(JSON.stringify(p)+'\\n');fs.appendFileSync(${JSON.stringify(log)},JSON.stringify({boot:process.pid})+'\\n');rl.createInterface({input:process.stdin}).on('line',line=>{const p=JSON.parse(line);fs.appendFileSync(${JSON.stringify(log)},line+'\\n');if(!p.method){const call=calls.get(p.id);if(call&&!call.stopped){out({method:'item/agentMessage/delta',params:{threadId:call.threadId,delta:call.text}});call.timer=setTimeout(()=>out({method:'turn/completed',params:{threadId:call.threadId,turn:{id:call.turnId,status:'completed'}}}),call.text==='slow'?800:200);}return;}if(p.method==='initialized')return;let result={};if(p.method==='thread/start')result={thread:{id:'t'+(++sequence)}};if(p.method==='turn/start'){const threadId=p.params.threadId,turnId='u'+(++sequence),text=p.params.input[0].text;result={turn:{id:turnId}};const call={threadId,turnId,text};turns.set(threadId,call);const id=++toolId;calls.set(id,call);setTimeout(()=>out({id,method:'item/tool/call',params:{threadId,turnId,callId:String(id),tool:'publish_canvas',arguments:{text}}}),10);}if(p.method==='turn/interrupt'){const call=turns.get(p.params.threadId);if(call){call.stopped=true;clearTimeout(call.timer);}out({method:'turn/completed',params:{threadId:p.params.threadId,turn:{id:p.params.turnId,status:'interrupted'}}});}out({id:p.id,result});if(p.method==='test/crash')setTimeout(()=>process.exit(0),20);});`);
 const client=new CodexClient(home),tools:string[]=[],texts={a:'',b:''};let a:CodexRun|undefined,b:CodexRun|undefined;
 const wait=async(check:()=>boolean)=>{const end=Date.now()+5000;while(!check()){assert(Date.now()<end,'Pool event timed out');await new Promise(r=>setTimeout(r,10));}};
 const make=(id:'a'|'b')=>new CodexRun({client,home,cwd:root,chat:{id,title:id,provider:'openai-codex',model:'gpt-6-luna',thinking:'low',messages:[],draft:'',draftAttachments:[],updatedAt:0},systemPrompt:'Scoped teacher',tools:[],execute:async(_name,args)=>{tools.push(id+':'+args.text);return{content:[{type:'text',text:id}]};},delta:t=>{texts[id]+=t;},activity:()=>{}});
 try{
  await Promise.all([client.start(),client.start(),client.start()]);a=make('a');b=make('b');const pa=a.prompt('slow'),pb=b.prompt('normal');await wait(()=>tools.length===2);await a.stop();await Promise.all([pa,pb]);assert.equal(texts.b,'normal');assert(!texts.a.includes('normal'));assert.deepEqual(tools.sort(),['a:slow','b:normal']);
  await b.prompt('follow-up');assert.equal(texts.b,'normalfollow-up');let packets=(await readFile(log,'utf8')).trim().split('\n').map(l=>JSON.parse(l));assert.equal(packets.filter(p=>p.boot).length,1);assert.equal(packets.filter(p=>p.method==='initialize').length,1);assert.equal(packets.filter(p=>p.method==='thread/start').length,2);const turns=packets.filter(p=>p.method==='turn/start');assert.equal(turns[1].params.threadId,turns[2].params.threadId);assert(turns.every(p=>p.params.effort==='low'));for(const p of packets.filter(p=>p.result?.contentItems))assert.equal(p.result.contentItems[0].text,p.id===101?'a':'b');
  await client.request('test/crash');await wait(()=>!b!.hasContext());await b.prompt('recovered');assert(String(texts.b).endsWith('recovered'));packets=(await readFile(log,'utf8')).trim().split('\n').map(l=>JSON.parse(l));assert.equal(packets.filter(p=>p.boot).length,2);assert.equal(packets.filter(p=>p.method==='thread/start').length,3);
 }finally{a?.close();b?.close();client.close();await rm(root,{recursive:true,force:true});}
});
