import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync} from 'node:child_process';import {createSecureServer} from 'node:http2';
import {JevTransport} from '../src/jev-transport.ts';
test('HTTP/2 judge multiplexes checks and cancels one answer without reopening TLS',async()=>{
 const root=await mkdtemp(join(tmpdir(),'loom-h2-'));const cert=join(root,'cert.pem'),key=join(root,'key.pem');execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-days','1','-subj','/CN=localhost','-addext','subjectAltName=IP:127.0.0.1'],{stdio:'ignore'});
 const server=createSecureServer({key:await readFile(key),cert:await readFile(cert),allowHTTP1:true});let sessions=0,received=0;server.on('session',()=>sessions++);server.on('stream',(stream,headers)=>{stream.on('error',()=>{});if(headers[':method']==='HEAD'){stream.respond({':status':200});stream.end();return;}let body='';stream.on('data',chunk=>body+=chunk);stream.on('end',()=>{received++;setTimeout(()=>{if(!stream.destroyed){stream.respond({':status':200,'content-type':'application/json'});stream.end(JSON.stringify({answer:body}));}},body==='old'?200:20);});});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url=`https://127.0.0.1:${(server.address() as any).port}`,transport=new JevTransport({connect:{ca:await readFile(cert)}});
 const wait=async(fn:()=>boolean)=>{const end=Date.now()+3000;while(!fn()){assert(Date.now()<end);await new Promise(r=>setTimeout(r,10));}};
 try{transport.warm(url);await wait(()=>sessions===1);const abort=new AbortController();const old=transport.fetch(url,{method:'POST',body:'old',signal:abort.signal});void old.catch(()=>{});await wait(()=>received===1);abort.abort();await assert.rejects(old);const responses=await Promise.all(['new','another'].map(async body=>(await transport.fetch(url,{method:'POST',body})).json()));assert.deepEqual(responses,[{answer:'new'},{answer:'another'}]);assert.equal(received,3);assert.equal(sessions,1,'Cancelled checks retain the same HTTP/2 connection');}
 finally{await transport.close();await new Promise<void>(r=>server.close(()=>r()));await rm(root,{recursive:true,force:true});}
});
