import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, mkdir, stat, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { Memory } from '../src/memory.ts';
import { PDFService } from '../src/pdf.ts';
import { importAutoum } from '../src/auth-import.ts';
import { publicURL, downloadPaper, searchPapers } from '../src/papers.ts';
import { pdfFixture } from './fixtures.ts';
const temp=()=>mkdtemp(join(tmpdir(),'loom-library-'));
test('OptMem notes survive concurrent writes/restart; bounded summaries can be zoomed, repaired, and searched',async()=>{
  const root=await temp();try{const m=new Memory(root);await Promise.all(Array.from({length:128},(_,i)=>m.note(`Finding ${i}: α waves have frequency ${i} Hz.`)));await assert.rejects(m.note('α'.repeat(141)),/280/);const log=await readFile(join(root,'LOG.txt'));assert.equal(log.length,128*320);let pending=await m.pending();while(pending){await m.merge(pending.id,`Summary of findings ${pending.id}.`);pending=await m.pending();}const wake=await m.wake(16);assert.equal(wake.total,128);assert(wake.lines.length<=16);assert(wake.lines.some(l=>l.includes('Finding 127')));assert(wake.lines.some(l=>l.includes('Summary')));
    assert.deepEqual(await readFile(join(root,'LOG.txt')),log);const reopened=new Memory(root);assert((await reopened.recall('frequency 79 Hz')).matches[0].includes('Finding 79'));assert.equal((await reopened.zoom('0-1')).length,2);assert((await reopened.zoom('0-1'))[0].includes('Finding 0'));await reopened.forget('0-3');assert.equal((await reopened.pending())?.id,'0-3');assert.deepEqual(await readFile(join(root,'LOG.txt')),log);await assert.rejects(reopened.merge('4-7','Out of order'),/pending/);await writeFile(join(root,'LOG.txt'),Buffer.from('partial'),{flag:'a'});assert.equal((await reopened.wake()).total,128);assert.equal((await stat(join(root,'LOG.txt'))).size,log.length);assert((await reopened.note('Finding 127: α waves have frequency 127 Hz.')).duplicate);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('PDF worker reads actual page text and renders equations/layout independently from the UI',async()=>{
  const root=await temp();try{const path=join(root,'source.pdf');await writeFile(path,pdfFixture());const pdf=new PDFService(resolve('dist/pdf-worker.mjs'));const info=await pdf.read(path,'info');assert.equal(info.total,2);const text=await pdf.read(path,'text',[2]);assert.equal(text.pages.length,1);assert.equal(text.pages[0].page,2);assert.match(text.pages[0].text,/maximum displacement/);const passage=await pdf.read(path,'search',undefined,'MAXIMUM displacement');assert.equal(passage.matches.length,1);assert.equal(passage.matches[0].page,2);assert.match(passage.matches[0].excerpt,/maximum displacement/);assert.equal((await pdf.read(path,'search',undefined,'not in this source')).matches.length,0);await assert.rejects(pdf.read(path,'search',undefined,' '),/phrase/);const image=await pdf.read(path,'render',[1]);assert.match(image.pages[0].dataUrl,/^data:image\/png;base64,/);assert.equal(image.pages[0].width,1200);assert(image.pages[0].height>1200);assert((await pdf.read(path,'tables',[1])).pages.length);await assert.rejects(pdf.read(path,'text',[0]),/valid pages/);await writeFile(join(root,'fake.pdf'),'a fake document');await assert.rejects(pdf.read(join(root,'fake.pdf')),/does not contain/);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('Autoum import copies supported primary/named accounts without overwriting Loom or returning credentials',async()=>{
  const root=await temp();try{const source=join(root,'Autoum'),dest=join(root,'Loom'),native=join(root,'native'),id='12345678-1234-1234-1234-123456789012';await Promise.all([mkdir(join(source,'pi'),{recursive:true}),mkdir(join(source,'accounts',id),{recursive:true}),mkdir(join(dest,'pi'),{recursive:true}),mkdir(native)]);await writeFile(join(source,'pi/auth.json'),JSON.stringify({'opencode-go':{type:'api_key',key:'source-go'},'openai-codex':{type:'oauth',access:'access',refresh:'refresh',accountId:'account'}}));await writeFile(join(source,'accounts.json'),JSON.stringify([{id,provider:'opencode'}]));await writeFile(join(source,'accounts',id,'auth.json'),JSON.stringify({opencode:{type:'api_key',key:'source-zen'}}));await writeFile(join(dest,'pi/auth.json'),JSON.stringify({'opencode-go':{type:'api_key',key:'existing-go'}}));await writeFile(join(native,'auth.json'),JSON.stringify({OPENAI_API_KEY:'excluded-api-key',tokens:{access_token:'access',refresh_token:'refresh',id_token:'id',account_id:'account'}}));const result=await importAutoum(dest,source,native);assert.deepEqual(result,{imported:['openai-codex','opencode'],nativeImported:true});const auth=JSON.parse(await readFile(join(dest,'pi/auth.json'),'utf8'));assert.equal(auth['opencode-go'].key,'existing-go');assert.equal(auth.opencode.key,'source-zen');assert(!JSON.stringify(result).includes('source-zen'));assert.equal(JSON.parse(await readFile(join(dest,'codex/auth.json'),'utf8')).OPENAI_API_KEY,undefined);assert.equal((await stat(join(dest,'pi/auth.json'))).mode&0o777,0o600);assert.equal((await importAutoum(dest,source,native)).imported.length,0);
  }finally{await rm(root,{recursive:true,force:true});}
});
test('paper downloads reject local/private endpoints and non-HTTPS sources before fetching',async()=>{
  for(const url of ['http://arxiv.org/pdf/1706.03762','https://localhost/paper.pdf','https://127.0.0.1/paper.pdf','https://10.0.0.1/paper.pdf','https://[::1]/paper.pdf','https://user:pass@example.com/paper.pdf','https://example.com:8000/paper.pdf'])await assert.rejects(publicURL(url));
});
test('paper search parses source metadata and downloads retain provenance without replacing files',async()=>{
  const root=await temp();try{let seen='';const transport=async(url:string)=>{seen=url;return{url,response:new Response(new Uint8Array(pdfFixture()))};};const r=await downloadPaper(root,'https://arxiv.org/abs/1706.03762','attention',transport);assert.equal(seen,'https://arxiv.org/pdf/1706.03762');assert.equal(r.path,'papers/attention.pdf');assert.deepEqual(await readFile(join(root,r.path)),pdfFixture());const source=JSON.parse(await readFile(join(root,r.path+'.source.json'),'utf8'));assert.equal(source.requestedURL,'https://arxiv.org/abs/1706.03762');await assert.rejects(downloadPaper(root,source.requestedURL,'attention',transport),/EEXIST/);await assert.rejects(downloadPaper(root,source.requestedURL,'bad',async url=>({url,response:new Response('<html>Paywall</html>')})),/did not return a PDF/);
    const results=await searchPapers('ti:fixture',async url=>({url,response:new Response('<feed><entry><id>http://arxiv.org/abs/1234.5678</id><title>Research &amp; learning</title><summary>An abstract.</summary><published>2026-10-08</published><author><name>A. Author</name></author></entry></feed>')}));assert.equal(results[0].title,'Research & learning');assert.equal(results[0].pdfURL,'https://arxiv.org/pdf/1234.5678');assert.deepEqual(results[0].authors,['A. Author']);
  }finally{await rm(root,{recursive:true,force:true});}
});
