import {_electron as electron,type ElectronApplication} from 'playwright-core';
import {mkdtemp,readFile,rm,mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {request,Agent} from 'node:https';
import assert from 'node:assert/strict';
import type {PublicState} from '../src/shared.ts';

const data=await mkdtemp(join(tmpdir(),'loom-desktop-phone-'));let app:ElectronApplication|undefined,agent:Agent|undefined;const checks:string[]=[],errors:string[]=[];let url='',token='';
const rpc=(method:string,value:any={})=>new Promise<any>((resolve,reject)=>{const req=request(url+'/rpc',{method:'POST',agent,headers:{'Content-Type':'application/json',authorization:'Bearer '+token}},res=>{let body='';res.on('data',chunk=>body+=chunk);res.on('end',()=>{const result=JSON.parse(body);result.error?reject(Error(result.error)):resolve(result.result);});});req.on('error',reject);req.end(JSON.stringify({method,data:value}));});
const wait=async(fn:()=>Promise<boolean>,timeout=10000)=>{const end=Date.now()+timeout;while(!await fn()){assert(Date.now()<end,'The desktop phone action timed out');await new Promise(r=>setTimeout(r,50));}};
const launch=async()=>{app=await electron.launch({executablePath:process.env.ELECTRON_PATH||'release/linux-unpacked/loom-studio',args:['.','--no-sandbox','--ozone-platform=x11'],env:{...process.env,STUDIO_DATA_DIR:data}});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.locator('.app').waitFor();return page;};
try{
 let page=await launch();await page.getByRole('button',{name:'Settings & connections',exact:true}).click();await page.getByRole('button',{name:'Phone',exact:true}).click();await page.getByRole('button',{name:'Enable phone connection',exact:true}).click();await page.getByRole('img',{name:'Android pairing QR code'}).waitFor();assert((await page.getByRole('img',{name:'Android pairing QR code'}).getAttribute('src'))!.startsWith('data:image/png'));
 const config=JSON.parse(await readFile(join(data,'phone/connection.json'),'utf8'));url='https://127.0.0.1:'+config.port;token=config.token;agent=new Agent({ca:config.cert,checkServerIdentity:()=>undefined,keepAlive:true});checks.push('packaged desktop Settings enables a real encrypted phone listener');
 const initial=await rpc('state') as PublicState;assert(initial.chats.length);assert(initial.providers.every(p=>Array.isArray(p.models)));assert(!JSON.stringify(initial).includes(token));checks.push('phone API reads the actual worker state and model capabilities');
 const project=await rpc('mobileCreateProject',{name:'Phone study'});const chat=await rpc('newChat',{projectId:project.id});await rpc('createFolder',{kind:'disk',chatId:chat.id,name:'papers'});assert((await rpc('listFiles',{chatId:chat.id})).some((f:any)=>f.name==='papers'&&f.directory));checks.push('phone creates real desktop projects, chats, and disk folders');
 const attachment=await rpc('mobileUpload',{chatId:chat.id,name:'notes.txt',mime:'text/plain',bytes:Buffer.from('A phone attachment.').toString('base64')});const downloaded=await rpc('mobileAttachment',{id:attachment.id});assert.equal(Buffer.from(downloaded.bytes,'base64').toString(),'A phone attachment.');await rpc('saveDraft',{chatId:chat.id,text:'A draft from the phone'});await wait(async()=>await page.getByRole('textbox',{name:'Message',exact:true}).inputValue()==='A draft from the phone');checks.push('native upload data reaches the worker and phone drafts update the desktop');
 const sample=await rpc('sample');const current=await rpc('state') as PublicState;const canvas=current.canvases.find(c=>c.chatId===sample.id)!;const full=await rpc('getCanvas',{id:canvas.id});assert(full.html.includes('Sine wave'));await rpc('canvasState',{id:canvas.id,state:{amplitude:1.8}});assert.equal((await rpc('getCanvas',{id:canvas.id})).state.amplitude,1.8);checks.push('actual desktop lessons and saved interaction state are available to Android');
 await app!.close();app=undefined;page=await launch();await wait(async()=>{try{return(await rpc('state')).activeChatId===sample.id;}catch{return false;}},20000);checks.push('enabled pairing restores across a desktop restart');
 await page.getByRole('button',{name:'Settings & connections',exact:true}).click();await page.getByRole('button',{name:'Phone',exact:true}).click();await page.getByRole('button',{name:'Revoke paired phones',exact:true}).click();await wait(async()=>{try{await rpc('state');return false;}catch(e){return String(e).includes('revoked');}});await page.getByRole('button',{name:'Disable phone connection',exact:true}).click();await page.getByRole('button',{name:'Enable phone connection',exact:true}).waitFor();checks.push('desktop revoke and disable controls end phone access');
 assert.deepEqual(errors,[]);await mkdir('test-results',{recursive:true});await writeFile('test-results/phone-desktop-report.json',JSON.stringify({checks,errors,fixture:'Packaged Electron application, real worker/Store/phone API, private temporary workspace. No model requests.'},null,2));console.log(checks.length+' packaged desktop phone checks passed.');
}catch(e){console.error(e);process.exitCode=1;}
finally{await app?.close().catch(()=>{});agent?.destroy();await rm(data,{recursive:true,force:true,maxRetries:3,retryDelay:100});}
