import {_electron as electron,type ElectronApplication,type Page} from 'playwright-core';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,copyFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {homedir,tmpdir} from 'node:os';
import {Store} from '../src/store.ts';
import type {Canvas,PublicState} from '../src/shared.ts';
import {teachingCases} from './teaching-cases.ts';

if(process.env.LOOM_LIVE_TEST!=='1')throw Error('Set LOOM_LIVE_TEST=1. This test makes real Go and Jev requests.');
const root=resolve('test-results/providers'),manifestPath=join(root,'session.json');await mkdir(root,{recursive:true});
const mode=process.argv[2]||'generate';
let app:ElectronApplication|undefined,page!:Page;const errors:string[]=[];
const state=()=>page.evaluate(()=>window.studio.call<PublicState>('state'));
async function until(fn:()=>Promise<boolean>,label:string,ms=240000){const end=Date.now()+ms;while(!await fn()){assert(Date.now()<end,label);await new Promise(r=>setTimeout(r,100));}}
async function launch(data:string){
 const env=Object.fromEntries(Object.entries({...process.env,STUDIO_DATA_DIR:data}).filter((x):x is [string,string]=>typeof x[1]==='string'&&x[0]!=='ELECTRON_RUN_AS_NODE'));
 app=await electron.launch({executablePath:process.env.ELECTRON_PATH||resolve('node_modules/electron/dist/electron'),args:['.','--no-sandbox','--ozone-platform=x11','--force-device-scale-factor=1'],env});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1440,900));page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.locator('.app').waitFor();await page.evaluate(()=>window.studio.call('refreshAccounts'));
}
async function select(id:string){await page.evaluate(id=>window.studio.call('selectChat',{id}),id);await until(async()=>await state().then(s=>s.activeChatId===id),'Chat selected',10000);await page.waitForTimeout(250);}
try{
 if(mode==='generate'){
  const data=await mkdtemp(join(tmpdir(),'loom-providers-'));await mkdir(join(data,'pi'),{mode:0o700});
  const auth=JSON.parse(await readFile(join(process.env.LOOM_ACCOUNT_DIR||join(homedir(),'.config/Loom'),'pi/auth.json'),'utf8'));assert(auth['opencode-go']&&auth.opencode);
  await writeFile(join(data,'pi/auth.json'),JSON.stringify({'opencode-go':auth['opencode-go'],opencode:auth.opencode}),{mode:0o600});
  const source=process.env.LOOM_TEST_SOURCE||join(root,'Stanford-linear-backprop.pdf');
  if(!process.env.LOOM_TEST_SOURCE){try{await readFile(source);}catch{const response=await fetch(teachingCases.find(c=>c.id==='backprop')!.url,{signal:AbortSignal.timeout(30000)});assert(response.ok);const bytes=Buffer.from(await response.arrayBuffer());assert(bytes.subarray(0,1024).includes(Buffer.from('%PDF-')));await writeFile(source,bytes);}}
  const store=new Store(data);await store.init();Object.assign(store.db.settings,{theme:'light',fontSize:18,judge:'opencode',judgeModel:'jev-1.13-free',customPrompt:''});
  const m:any={data,cases:[],errors:[]};
  for(const condition of ['empty','sources']){
   const directory=join(data,condition);await mkdir(directory);
   if(condition==='sources')await copyFile(source,join(directory,'Stanford-linear-backprop.pdf'));
   const project=await store.createProject('Go backpropagation · '+condition,directory),chat=await store.newChat({projectId:project.id,provider:'opencode-go',model:'gpt-6-luna'});chat.thinking='low';chat.title='Backpropagation · '+condition;
   m.cases.push({condition,chatId:chat.id,model:'gpt-6-luna',thinking:'low',provider:'opencode-go'});
  }
  const gemini=await store.newChat({provider:'gemini-cli',model:'gemini-3.8-flash'});gemini.title='Gemini 3.8 Flash route';m.gemini={chatId:gemini.id,model:gemini.model};await store.commit();await writeFile(manifestPath,JSON.stringify(m,null,2),{mode:0o600});
  await launch(data);const s=await state();assert(s.providers.find(p=>p.id==='opencode-go')?.configured);assert(s.providers.find(p=>p.id==='opencode-go')?.models.find(x=>x.id==='gpt-6-luna')?.thinking?.some(t=>t.value==='low'));assert.equal(s.settings.customPrompt,'');
  for(const c of m.cases){
   try{
    await select(c.chatId);const started=Date.now();let firstText:number|undefined;const prompt='Teach me backpropagation. I know basic calculus, but neural networks are new to me.';c.prompt=prompt;
    await page.getByRole('textbox',{name:'Message',exact:true}).fill(prompt);await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');
    await until(async()=>{const s=await state(),run=s.runs.find(x=>x.chatId===c.chatId);if(run?.error)throw Error(run.error);if(firstText===undefined&&run?.text.trim())firstText=Date.now()-started;return !!run&&!run.busy;},'Go must complete the teaching request');c.completeMs=Date.now()-started;c.firstTextMs=firstText;
    const end=await state();assert.equal(end.chats.find(x=>x.id===c.chatId)?.model,c.model);assert.equal(end.chats.find(x=>x.id===c.chatId)?.thinking,'low');
    const meta=end.canvases.find(x=>x.chatId===c.chatId);assert(meta,'A topic-only request must create its own interactive lesson');c.canvasId=meta.id;
    await page.locator(`iframe[src^="studio://canvas/${meta.id}?"]`).waitFor();const f=page.frames().find(f=>f.url().startsWith('studio://canvas/'+meta.id+'?'))!;await f.locator('body').waitFor();await page.waitForTimeout(500);
    const canvas=await page.evaluate(id=>window.studio.call<Canvas>('getCanvas',{id}),meta.id);assert(canvas.rubric.length,'The lesson must choose a conceptual rubric');
    c.ui=await f.evaluate(()=>({text:document.body.innerText,math:document.querySelectorAll('.katex').length,mathErrors:document.querySelectorAll('.katex-error').length,overflow:document.documentElement.scrollWidth>innerWidth+1,controls:[...document.querySelectorAll('button,input,select,textarea,summary')].map(el=>({tag:el.tagName,id:el.id,type:el.getAttribute('type'),label:el.getAttribute('aria-label')||el.textContent}))}));
    assert(c.ui.math>0);assert.equal(c.ui.mathErrors,0);assert(!c.ui.overflow);assert(c.ui.controls.length>=3);assert.equal(await page.locator('.canvas-error').count(),0);assert(/Studio\.(?:bindQuiz|check)/.test(canvas.html));
    const folder=join(root,c.condition);await mkdir(folder,{recursive:true});await writeFile(join(folder,'canvas.json'),JSON.stringify(canvas,null,2));await writeFile(join(folder,'messages.json'),JSON.stringify(end.chats.find(x=>x.id===c.chatId)?.messages,null,2));await writeFile(join(folder,'ui.json'),JSON.stringify(c.ui,null,2));await page.screenshot({path:join(folder,'initial.png')});
    c.pass=true;console.log('LESSON',JSON.stringify({condition:c.condition,completeMs:c.completeMs,firstTextMs:c.firstTextMs,canvasId:c.canvasId,controls:c.ui.controls,rubric:canvas.rubric}));
   }catch(e){c.error=e instanceof Error?e.message:String(e);console.log('FAIL',c.condition,c.error);await page.screenshot({path:join(root,c.condition+'-failure.png')});await page.evaluate(id=>window.studio.call('stop',{chatId:id}),c.chatId).catch(()=>{});}
   await writeFile(manifestPath,JSON.stringify(m,null,2),{mode:0o600});
  }
  await select(gemini.id);const catalog=(await state()).providers.find(p=>p.id==='gemini-cli')!;m.gemini.available=catalog.available;m.gemini.catalog=catalog.models;
  if(!catalog.available||!catalog.models.some(x=>x.id==='gemini-3.8-flash')){
   await page.getByRole('textbox',{name:'Message',exact:true}).fill('Teach me backpropagation.');await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await page.getByRole('alert').filter({hasText:'Install and sign in'}).waitFor();
   m.gemini.error='Gemini 3.8 Flash is absent from the app catalog; the Gemini CLI runtime is not installed. Antigravity requires an app adapter.';m.gemini.visibleFailureVerified=true;assert.equal((await state()).canvases.filter(c=>c.chatId===gemini.id).length,0);await page.screenshot({path:join(root,'gemini-unavailable.png')});
  }else m.gemini.next='Run the gemini case to validate the available subscription route.';
  m.rendererErrors=errors;assert.deepEqual(errors,[]);await writeFile(manifestPath,JSON.stringify(m,null,2),{mode:0o600});await writeFile(join(root,'generation-report.json'),JSON.stringify({...m,data:undefined},null,2));console.log('SUMMARY',JSON.stringify({go:m.cases.map((c:any)=>({condition:c.condition,pass:c.pass,error:c.error})),gemini:m.gemini}));assert(m.cases.every((c:any)=>c.pass),'Every Go lesson must pass');
 }else if(mode==='gemini'||mode==='gemini-empty'){
  const m=JSON.parse(await readFile(manifestPath,'utf8'));await launch(m.data);const s=await state(),provider=s.providers.find(p=>p.id==='gemini-cli')!,model=provider.models.find(x=>x.id==='gemini-3.8-flash');assert(provider.configured&&model,'Gemini 3.8 Flash must be in the real subscription catalog');assert(model.thinking?.some(t=>t.value==='low'));
  const chat=await page.evaluate(data=>window.studio.call('newChat',data),{provider:'gemini-cli',model:model.id,projectId:s.chats.find(c=>c.id===m.cases.find((c:any)=>c.condition===(mode==='gemini-empty'?'empty':'sources')).chatId)!.projectId});
  await page.evaluate(data=>window.studio.call('updateChat',data),{id:chat.id,thinking:'low',title:'Gemini 3.8 Flash · '+(mode==='gemini-empty'?'empty':'sources')});await select(chat.id);
  const report:any={provider:'gemini-cli',route:provider.detail,model:model.id,thinking:'low',catalog:model,chatId:chat.id,condition:mode==='gemini-empty'?'empty':'sources',prompt:'Teach me backpropagation. I know basic calculus, but neural networks are new to me.'};if(mode==='gemini-empty')m.geminiEmpty=report;else m.gemini=report;
  await writeFile(manifestPath,JSON.stringify(m,null,2),{mode:0o600});
  const start=Date.now();let firstText:number|undefined;await page.getByRole('textbox',{name:'Message',exact:true}).fill(report.prompt);await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');
  await until(async()=>{const s=await state(),run=s.runs.find(r=>r.chatId===chat.id);if(run?.error)throw Error(run.error);if(firstText===undefined&&run?.text.trim())firstText=Date.now()-start;return !!run&&!run.busy;},'Actual Gemini must complete the lesson');report.completeMs=Date.now()-start;report.firstTextMs=firstText;
  const end=await state();assert.equal(end.chats.find(c=>c.id===chat.id)?.model,model.id);assert.equal(end.chats.find(c=>c.id===chat.id)?.thinking,'low');const meta=end.canvases.find(c=>c.chatId===chat.id);assert(meta,'Gemini must independently choose an interactive lesson');report.canvasId=meta.id;
  await page.locator(`iframe[src^="studio://canvas/${meta.id}?"]`).waitFor();const f=page.frames().find(f=>f.url().startsWith('studio://canvas/'+meta.id+'?'))!;await f.locator('body').waitFor();await page.waitForTimeout(500);
  const canvas=await page.evaluate(id=>window.studio.call<Canvas>('getCanvas',{id}),meta.id);assert(canvas.rubric.length);assert.equal(await page.locator('.canvas-error').count(),0);assert.equal(await f.locator('.katex-error').count(),0);assert(await f.locator('.katex').count()>0);assert(await f.locator('svg,canvas,.flow-node,[role=img]').count()>0);assert(await f.locator('button,input,select,textarea,summary').count()>3);assert(/Studio\.(?:bindQuiz|check)/.test(canvas.html));
  const folder=join(root,mode==='gemini-empty'?'gemini-empty':'gemini');await mkdir(folder,{recursive:true});await writeFile(join(folder,'canvas.json'),JSON.stringify(canvas,null,2));await writeFile(join(folder,'messages.json'),JSON.stringify(end.chats.find(c=>c.id===chat.id)?.messages,null,2));report.ui=await f.evaluate(()=>({text:document.body.innerText,controls:[...document.querySelectorAll('input,textarea,button,select,summary')].map(e=>({id:e.id,tag:e.tagName,type:e.getAttribute('type'),label:e.getAttribute('aria-label')||e.textContent}))}));await writeFile(join(folder,'ui.json'),JSON.stringify(report.ui,null,2));await page.screenshot({path:join(folder,'initial.png')});report.generation=true;
  await writeFile(manifestPath,JSON.stringify(m,null,2),{mode:0o600});await writeFile(join(root,mode==='gemini-empty'?'gemini-empty-report.json':'gemini-report.json'),JSON.stringify(report,null,2));console.log('GEMINI',JSON.stringify({...report,ui:{...report.ui,text:undefined}}));
 }else if(mode==='gemini-empty-review'){
  const m=JSON.parse(await readFile(manifestPath,'utf8')),r=m.geminiEmpty;await launch(m.data);await select(r.chatId);const s=await state(),chat=s.chats.find(c=>c.id===r.chatId)!;const meta=s.canvases.find(c=>c.chatId===r.chatId)!;assert(meta);r.canvasId=meta.id;await page.locator(`iframe[src^="studio://canvas/${meta.id}?"]`).waitFor();const f=page.frames().find(f=>f.url().startsWith('studio://canvas/'+meta.id+'?'))!;await f.locator('#input-x').waitFor();await page.waitForTimeout(400);assert.equal(await page.locator('.canvas-error').count(),0);assert.equal(await f.locator('.katex-error').count(),0);assert(await f.locator('.flow-node .katex').count()>3);r.figureFormat='DOM computation graph';r.generation=true;r.completeMs=chat.messages.at(-1)!.at-chat.messages[0].at;
  const change=async(id:string,value:string)=>f.locator(id).evaluate((el,v)=>{(el as HTMLInputElement).value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},value);await change('#input-x','1.3');await page.waitForTimeout(400);const exact=await page.evaluate(id=>window.studio.call<Canvas>('getCanvas',{id}),meta.id);assert.equal((exact.state as any).x,1.3);const before=exact.state as any;const a=1/(1+Math.exp(-(before.w1*before.x+before.b1))),dy=before.w2*a-before.y,delta=dy*before.w2*a*(1-a);await f.locator('#btn-step').click();await page.waitForTimeout(400);const stepped=await page.evaluate(id=>window.studio.call<Canvas>('getCanvas',{id}),meta.id);assert(Math.abs((stepped.state as any).w1-(before.w1-.5*delta*before.x))<1e-10);r.exactGradientStep=true;
  await page.screenshot({path:join(root,'gemini-empty/initial.png')});await app!.close();app=undefined;await launch(m.data);await select(r.chatId);await page.locator(`iframe[src^="studio://canvas/${meta.id}?"]`).waitFor();const restored=page.frames().find(f=>f.url().startsWith('studio://canvas/'+meta.id+'?'))!;assert.equal(await restored.locator('#input-x').inputValue(),'1.3');const saved=await page.evaluate(id=>window.studio.call<Canvas>('getCanvas',{id}),meta.id);assert.deepEqual(saved.state,stepped.state);r.controlsRestart=true;assert.deepEqual(errors,[]);await writeFile(join(root,'gemini-empty-report.json'),JSON.stringify(r,null,2));await writeFile(manifestPath,JSON.stringify(m,null,2),{mode:0o600});console.log('GEMINI EMPTY',JSON.stringify(r));
 }else if(mode==='gemini-interact'){
  const m=JSON.parse(await readFile(manifestPath,'utf8')),r=JSON.parse(await readFile(join(root,'gemini-report.json'),'utf8'));await launch(m.data);await select(r.chatId);await page.locator(`iframe[src^="studio://canvas/${r.canvasId}?"]`).waitFor();const f=page.frames().find(f=>f.url().startsWith('studio://canvas/'+r.canvasId+'?'))!;await f.locator('#sl-x').waitFor();
  const change=async(id:string,value:string)=>f.locator(id).evaluate((el,value)=>{(el as HTMLInputElement).value=value;el.dispatchEvent(new Event('input',{bubbles:true}));},value);
  await change('#sl-x','1.3');await change('#sl-w','1');await change('#sl-b','0');await change('#sl-yt','0');const a=1/(1+Math.exp(-1.3)),loss=.5*a*a,gradient=a*a*(1-a)*1.3;const values=await f.locator('#table-body tr td:nth-child(2)').allTextContents();assert(Math.abs(Number(values[0])-loss)<.0001);assert(Math.abs(Number(values[1])-a)<.0001);assert.match((await f.locator('#comp-graph').textContent())||'',new RegExp(gradient.toFixed(3).replace('.','\\.')));r.arithmetic=true;
  await f.locator('#btn-reset').click();const before=Number((await f.locator('#table-body tr td:nth-child(2)').allTextContents())[0]);const initialA=1/(1+Math.exp(-1)),expectedW=1.5-.5*initialA*initialA*(1-initialA);await f.locator('#btn-step').click();const after=Number((await f.locator('#table-body tr td:nth-child(2)').allTextContents())[0]);assert(after<before);r.gradientStep={lossBefore:before,lossAfter:after,expectedWeight:expectedW,actualWeight:Number(await f.locator('#sl-w').inputValue())};r.gradientStep.exact=Math.abs(r.gradientStep.expectedWeight-r.gradientStep.actualWeight)<1e-9;
  await f.evaluate(()=>{const studio=(window as any).Studio,check=studio.check.bind(studio);(window as any).__checks=[];studio.check=async(answer:any)=>{const c:any={answer,start:performance.now(),pending:true};(window as any).__checks.push(c);try{c.result=await check(answer);return c.result;}catch(e){c.error=String(e);throw e;}finally{c.ms=performance.now()-c.start;c.pending=false;}};});
  const wrong='The derivative approaching zero amplifies earlier gradients. The chain rule adds all local derivatives along one path, so those weights learn faster.';const correct='By the chain rule, local derivatives multiply along a connected path to the loss. A nearly zero activation derivative makes gradients for earlier weights on that path shrink toward zero: the vanishing gradient problem. Their gradient-descent updates become very small, so learning slows or stalls. A separate bypass path can still contribute its own gradient.';
  const input=f.locator('#quiz-input');const check=async(answer:string)=>{const n=await f.evaluate(()=>(window as any).__checks.length);await input.fill(answer);await until(()=>f.evaluate(n=>{const c=(window as any).__checks;return c.length>n&&!c.at(-1).pending;},n),'Gemini lesson must use real Jev',30000);const c=await f.evaluate(()=>(window as any).__checks.at(-1));assert(!c.error,c.error);return c;};r.wrong=await check(wrong);assert(r.wrong.result.items.some((i:any)=>i.status==='contradicted'));r.correct=await check(correct);assert(r.correct.result.items.every((i:any)=>i.status==='demonstrated'));
  await f.locator('#btn-quiz-detail').click();const composer=page.getByRole('textbox',{name:'Message',exact:true});await until(async()=>(await composer.inputValue()).includes(correct),'Detailed feedback uses the actual answer',10000);assert((await composer.inputValue()).includes('Published rubric:'));const start=Date.now();await composer.press('Enter');await until(async()=>{const run=(await state()).runs.find(x=>x.chatId===r.chatId);if(run?.error)throw Error(run.error);return !!run&&!run.busy;},'Actual Gemini feedback must finish');r.detailedMs=Date.now()-start;const end=await state();const chat=end.chats.find(c=>c.id===r.chatId)!;assert.equal(chat.model,'gemini-3.8-flash');assert.equal(chat.thinking,'low');r.detailedReply=chat.messages.filter(x=>x.role==='assistant'&&x.text).at(-1)?.text;assert(r.detailedReply?.length>80);assert.equal(await page.locator('.katex-error,.canvas-error').count(),0);await page.screenshot({path:join(root,'gemini/feedback.png')});r.liveFeedback=true;
  await app!.close();app=undefined;await launch(m.data);await select(r.chatId);await page.locator(`iframe[src^="studio://canvas/${r.canvasId}?"]`).waitFor();const restored=page.frames().find(f=>f.url().startsWith('studio://canvas/'+r.canvasId+'?'))!;assert.equal(await restored.locator('#quiz-input').inputValue(),correct);assert.equal(await page.locator('.canvas-error').count(),0);r.quizRestart=true;r.controlsPersistAuthored=/Studio.saveState/.test((await page.evaluate(id=>window.studio.call<Canvas>('getCanvas',{id}),r.canvasId)).html);assert.deepEqual(errors,[]);await writeFile(join(root,'gemini-report.json'),JSON.stringify(r,null,2));console.log('GEMINI INTERACTIONS',JSON.stringify({arithmetic:r.arithmetic,step:r.gradientStep,wrongMs:r.wrong.ms,correctMs:r.correct.ms,detailedMs:r.detailedMs,quizRestart:r.quizRestart,authoredControlPersistence:r.controlsPersistAuthored}));
 }else if(mode==='interact'){
  const m=JSON.parse(await readFile(manifestPath,'utf8'));await launch(m.data);const report:any[]=[];
  for(const c of m.cases){
   const r:any={condition:c.condition,model:c.model,thinking:c.thinking};report.push(r);
   try{
    assert(c.canvasId);await select(c.chatId);await page.locator(`iframe[src^="studio://canvas/${c.canvasId}?"]`).waitFor();const f=page.frames().find(f=>f.url().startsWith('studio://canvas/'+c.canvasId+'?'))!;
    const range=f.locator('input[type=range]').first();await range.waitFor();
    const change=async(value:string)=>range.evaluate((el,value)=>{(el as HTMLInputElement).value=value;el.dispatchEvent(new Event('input',{bubbles:true}));},value);
    if(c.condition==='empty'){
     const before=await f.locator('#values').innerText();await change('1.3');assert.equal(await f.locator('#scaleOut').innerText(),'1.30');assert.notEqual(await f.locator('#values').innerText(),before);
     await f.locator('#sign').fill('positive');await f.locator('#checkSign').click();assert.match(await f.locator('#signResult').innerText(),/Not quite/);await f.locator('#sign').fill('negative');await f.locator('#checkSign').click();assert.match(await f.locator('#signResult').innerText(),/Correct/);
    }else{
     await change('1');const p=1/(1+Math.exp(-1));assert(Math.abs(Number(await f.locator('#pred').innerText())-p)<.0001);assert(Math.abs(Number(await f.locator('#loss').innerText())-.5*p*p)<.000001);assert(Math.abs(Number(await f.locator('#grad').innerText())-p*p*(1-p))<.000001);
     await f.locator('#reset').click();await f.locator('#guess').fill('-.125');await f.locator('#check').click();assert.match(await f.locator('#checkout').innerText(),/Not quite/);await f.locator('#guess').fill('.125');await f.locator('#check').click();assert.match(await f.locator('#checkout').innerText(),/Correct/);
     await f.locator('#step').click();r.exactStep={expected:-.125,actual:Number(await range.inputValue())};r.exactStep.pass=Math.abs(r.exactStep.actual-r.exactStep.expected)<1e-9;
    }
    r.exactPractice=true;r.slider=true;
    await f.evaluate(()=>{const studio=(window as any).Studio,check=studio.check.bind(studio);(window as any).__checks=[];studio.check=async(answer:any)=>{const call:any={answer,start:performance.now(),pending:true};(window as any).__checks.push(call);try{call.result=await check(answer);return call.result;}catch(e){call.error=String(e);throw e;}finally{call.pending=false;call.ms=performance.now()-call.start;}};});
    const input=f.locator('textarea').first();
    const wrong=c.condition==='empty'?'The raw loss passes backward unchanged. The downstream weight is an added penalty and the activation derivative is just the activation value. The chain rule does not combine local derivatives.':'The chain rule adds the local derivatives along one path. A shared node chooses the largest downstream gradient and ignores other paths.';
    const correct=c.condition==='empty'?'The downstream output weight is the derivative of the output weighted sum with respect to the hidden activation. The hidden activation derivative converts pre-activation changes into activation changes. The chain rule multiplies these local sensitivities along the path to the loss, together with the incoming loss derivative. The result measures how changing a hidden weight changes the loss.':'Along a sequence of operations, the chain rule multiplies local sensitivities to compose the effect of an earlier change on later values and the loss. A shared node affects the loss through each downstream branch. The multivariable chain rule adds all of those path contributions to give its total loss derivative; it does not pick only one branch.';
    const submit=async(answer:string)=>{const n=await f.evaluate(()=>(window as any).__checks.length);await input.fill(answer);await until(()=>f.evaluate(n=>{const calls=(window as any).__checks;return calls.length>n&&!calls.at(-1).pending;},n),'Jev feedback must complete',30000);const call=await f.evaluate(()=>(window as any).__checks.at(-1));assert(!call.error,call.error);return call;};
    r.wrong=await submit(wrong);assert(r.wrong.result.items.some((i:any)=>i.status==='contradicted'));r.correct=await submit(correct);assert(r.correct.result.items.every((i:any)=>i.status==='demonstrated'));
    const count=await f.evaluate(()=>(window as any).__checks.length);await input.fill(wrong+' I want to reconsider.');await until(()=>f.evaluate(n=>(window as any).__checks.length>n,count),'An old check must start',10000);await input.fill(correct);await until(()=>f.evaluate(n=>{const calls=(window as any).__checks;return calls.length>=n+2&&!calls.at(-1).pending;},count),'The revised answer must win',30000);r.editCalls=await f.evaluate(n=>(window as any).__checks.slice(n),count);assert(r.editCalls.at(-1).result?.items.every((i:any)=>i.status==='demonstrated'));
    await f.locator('#detail').click();const composer=page.getByRole('textbox',{name:'Message',exact:true});await until(async()=>(await composer.inputValue()).includes(correct),'Detailed feedback must use the actual attempt',10000);r.detailedDraft=await composer.inputValue();assert(r.detailedDraft.includes('Published rubric:'));const start=Date.now();await composer.press('Enter');await until(async()=>{const run=(await state()).runs.find(x=>x.chatId===c.chatId);if(run?.error)throw Error(run.error);return !!run&&!run.busy;},'Go detailed feedback must finish',120000);r.detailedMs=Date.now()-start;
    const end=await state();r.detailedReply=end.chats.find(x=>x.id===c.chatId)!.messages.at(-1)!.text;assert(r.detailedReply.length>80);assert.equal(end.chats.find(x=>x.id===c.chatId)?.model,'gpt-6-luna');assert.equal(end.chats.find(x=>x.id===c.chatId)?.thinking,'low');assert.equal(await page.locator('.markdown .katex-error').count(),0);assert.equal(await f.locator('.katex-error').count(),0);
    r.savedAnswer=correct;r.savedRange=await range.inputValue();await page.screenshot({path:join(root,c.condition,'feedback.png')});r.liveFeedback=true;
   }catch(e){r.error=e instanceof Error?e.message:String(e);await page.screenshot({path:join(root,c.condition+'-interaction-failure.png')});}
   await writeFile(join(root,'interaction-report.json'),JSON.stringify({report,errors},null,2));console.log('INTERACTION',JSON.stringify({condition:r.condition,error:r.error,slider:r.slider,liveFeedback:r.liveFeedback,wrongMs:r.wrong?.ms,correctMs:r.correct?.ms,exactStep:r.exactStep}));
  }
  await app!.close();app=undefined;await launch(m.data);
  for(const r of report){
   try{const c=m.cases.find((c:any)=>c.condition===r.condition);await select(c.chatId);await page.locator(`iframe[src^="studio://canvas/${c.canvasId}?"]`).waitFor();const f=page.frames().find(f=>f.url().startsWith('studio://canvas/'+c.canvasId+'?'))!;await page.waitForTimeout(500);assert.equal(await page.locator('.canvas-error').count(),0);assert.equal(await f.locator('input[type=range]').first().inputValue(),r.savedRange);assert.equal(await f.locator('textarea').first().inputValue(),r.savedAnswer);r.restart=true;}catch(e){r.restartError=e instanceof Error?e.message:String(e);await page.screenshot({path:join(root,r.condition+'-restart-failure.png')});}
  }
  await writeFile(join(root,'interaction-report.json'),JSON.stringify({report,errors},null,2));console.log('RESTART',JSON.stringify(report.map(r=>({condition:r.condition,pass:r.restart,error:r.restartError}))));assert(report.every(r=>!r.error&&r.restart),'Every Go interaction and restart must pass');
 }else if(mode==='cleanup'){
  const m=JSON.parse(await readFile(manifestPath,'utf8'));assert(m.data.startsWith(join(tmpdir(),'loom-providers-')));await rm(m.data,{recursive:true,force:true,maxRetries:5,retryDelay:200});await rm(manifestPath);
 }
}finally{await app?.close();}
