import {_electron as electron,type ElectronApplication,type Frame} from 'playwright-core';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import type {Canvas,PublicState} from '../src/shared.ts';
if(process.env.LOOM_TEACHING_LIVE!=='1')throw Error('Set LOOM_TEACHING_LIVE=1. This test uses real free Jev and selected Luna Low.');
const root=resolve('test-results/teaching'),manifest=JSON.parse(await readFile(join(root,'session.json'),'utf8'));
const answers:Record<string,{wrong:string;correct:string}>={
heaps:{wrong:'Every node must be sorted from left to right. Remove the last leaf and any child can be used to replace the root; both children are irrelevant.',correct:'A binary heap has a complete binary-tree shape and the parent-child order invariant. In a max-heap each parent is at least both children. Replace a removed root with the last leaf to keep the shape, then sift down by swapping with the larger child until the order is restored. Choosing the smaller child can leave the other child greater than its parent. Only this root-to-leaf path needs repair. For insertion, add the key at the next complete-tree leaf and sift upward along its ancestor path. Stop when the parent is at least the inserted key: that parent-child comparison and all untouched comparisons already satisfy max-heap order. In a min-heap reverse the comparisons and use the smaller child.'},
fft:{wrong:'The FFT approximates the DFT by dropping half the samples. The odd transform gets no phase factor and the second output is just a copy of the first.',correct:'Split the input into even and odd samples and recursively transform each half. The odd half is multiplied by the twiddle exp(-2 pi i k/N) because its original index is 2j+1. For each k reuse the same two values: X_k=E_k+W_N^k O_k and X_(k+N/2)=E_k-W_N^k O_k. Pairing shares work, and N work on each of log2 N recursive levels gives O(N log N), compared with O(N squared) direct DFT. This computes the same DFT, not an approximation.'},
backprop:{wrong:'The gradient is the loss value itself. Add it to every weight, skip intermediate derivatives, and the input never affects a weight gradient.',correct:'For z=wx+b, prediction a=sigmoid(z), and L=(a-t)^2/2, dL/da=a-t, da/dz=a(1-a), dz/dw=x. The chain rule multiplies these local derivatives along the path, giving dL/dw=(a-t)a(1-a)x and dL/db=(a-t)a(1-a). If a<t and x is positive then the weight gradient is negative: subtracting the gradient increases w and raises the prediction. At a reused intermediate node, sum contributions from every outgoing path. Reuse the saved activations and the same intermediate loss sensitivities across parameters, so a forward pass and a reverse pass replace separate full recomputations or perturbations for every weight. Compute all gradients before updating parameters. For a linear prediction instead, omit the sigmoid factor and use dL/dw=(wx+b-t)x.'},
attention:{wrong:'Softmax chooses only the biggest key and throws away every other value. Values determine the similarity score, and sqrt(d_k) is a normalization that makes the values add to one.',correct:'A query is compared with each key using a dot product, scaled by sqrt(d_k). Softmax turns those scores into nonnegative weights that sum to one; they are not a hard winner-take-all selection. The output is the weighted sum of the value vectors, so even a lower-scoring token can contribute. Increasing one score shifts more weight to its value and less to the others. Scaling the scores controls their variance as the key dimension grows and helps avoid a saturated softmax.'},
hecke:{wrong:'At q=1 the generator squares to zero. The braid relations disappear, so the generators commute and the algebra is just polynomials.',correct:'Use (T_i-q)(T_i+1)=0, so T_i squared=(q-1)T_i+q. The braid relations keep the Coxeter combinatorics. At q=1 the quadratic relation becomes T_i squared=1: T_i behaves like the corresponding simple reflection and the algebra specializes to the group algebra in this normalization. A parameter changes the multiplication rules while the standard T_w basis remains indexed by the same group elements. Away from q=1 the generators do not obey the involution relation.'},
cde:{wrong:'The cde triangle is an ADE or McKay graph. Its maps go from ordinary representations to a Dynkin diagram and then a surface; c is a tensor-product operation.',correct:'In the modular representation cde triangle, e lifts projectives from the residue field k to the fraction field K through a complete DVR R, d reduces an R-lattice modulo the maximal ideal to obtain a class over k, and c forgets projectivity and records composition factors. Thus c=d composed with e: lifting a projective lattice and reducing it gives the original projective module, with the same composition factors. In a splitting modular system, if D has ordinary irreducibles in rows and modular simples in columns, e has matrix D, d has matrix D transpose, and C=D transpose D. An irreducible characteristic-zero representation can reduce to a reducible k-module because modular reduction need not preserve semisimplicity or irreducibility; decomposition records the resulting composition-factor class rather than pretending the same simple survives. These conventions and splitting hypotheses matter.'},
cohomology:{wrong:'Every edge assignment is a gradient, even if the sum around a closed loop is nonzero. Filling the loop never changes cohomology.',correct:'A coboundary is a difference of vertex potentials along each oriented edge. Around a closed loop those differences telescope to zero, so a nonzero loop sum cannot be removed by changing vertex potentials. Cohomology identifies cocycles that differ by a coboundary. For an unfilled circle there are no 2-cells, so the edge cochains are cocycles and a nonzero circulation gives a nontrivial H^1 class. Adding the disk supplies a 2-cell and the cocycle condition forces the boundary sum to zero. Over a stated coefficient field the circle has a one-dimensional H^1 and the disk has zero H^1.'},
padic:{wrong:'Every automorphism acts nontrivially on the residue field. Inertia is the whole residue Galois group and Frobenius has a unique lift even in a ramified extension.',correct:'For a finite Galois extension L/K of p-adic fields, reduction gives a homomorphism G to the Galois group of the residue fields. Inertia I is its kernel: its elements act trivially on the residue field while they may act nontrivially in L. The fixed field of I is the maximal unramified subextension; the quotient G/I is cyclic and generated by residue Frobenius x maps to x^q. A lift of that generator to G is determined only modulo inertia, so it is generally not unique. Ramification index measures the remaining ramified part, while residue degree measures the unramified part. The two quadratic examples have the same abstract group C2 but different residue actions and ramification: Q5(sqrt(2)) has e=1,f=2 and trivial inertia, whereas Q5(sqrt(5)) is Eisenstein with e=2,f=1 and inertia equal to the whole group. Group order alone does not distinguish them.'},
riesz:{wrong:'The representing vector lies in the kernel and is unrelated to orthogonality. Every linear functional on any normed space has such a vector even if unbounded.',correct:'For a bounded linear functional on a Hilbert space, the kernel is a closed subspace. Its representing vector is orthogonal to the kernel, since f(m)=0 for m in the kernel and f(m) is its inner product with that vector. For nonzero f, choose the minimum-norm vector v0 in the affine slice f(v)=1. Varying v0 by t m for any m in the kernel shows v0 is orthogonal to m. Then u-f(u)v0 lies in the kernel, giving f(u)=inner(u,v0)/norm(v0)^2 in the convention linear in the first slot. The representing vector is v0/norm(v0)^2. In real R^2 with f(x,y)=a x+b y it is (a,b), so for f(x,y)=x+2y it is (1,2). If two vectors represent f, their difference has zero inner product with every u. Choose u equal to that difference to get its squared norm zero, so they coincide; in the complex convention conjugations must be handled consistently. Completeness and boundedness are required for this theorem.'}
};
const focused:Record<string,string>={
 'heaps-empty':'For a max-heap, each parent is at least its children. Sift-up compares the inserted key with its parent and stops when the parent is at least that key, so their comparison is valid. Only the new key and its ancestor path changed; every other parent-child comparison remains valid. Swaps along that path restore the invariant while retaining the complete-tree shape.',
 'heaps-sources':'Promote the larger child during delete-max. The promoted child must be at least both children, including its unswapped sibling. Promoting the smaller child could leave a larger sibling beneath it, violating max-heap order. Continue repairing only the replacement key’s downward path.',
 'fft-empty':'The even and odd samples give two smaller DFTs. Recursively compute each once and recombine with twiddle factors using sums and differences: Xk=Ek+Wk Ok and X(k+N/2)=Ek-Wk Ok. Shared subresults avoid recalculating every full sum. There is linear combination work per level and log2 N levels, hence O(N log N), with exactly the same DFT values.',
 'fft-sources':'Indices 2j and 2j+1 split the DFT into even and odd length-N/2 DFTs. The factor exp(-2 pi i k(2j)/N) is the length-N/2 phase. An odd index contributes one extra exp(-2 pi i k/N), the twiddle multiplying its smaller transform. Recombine as Ek+Wk Ok and Ek-Wk Ok for the paired outputs, reusing both smaller results.',
 'backprop-empty':'The chain rule multiplies local derivatives along each computational path to measure how a parameter change affects the loss. Contributions from multiple outgoing paths add at a reused node. Save activations on the forward pass and reuse each intermediate loss sensitivity on the backward pass for all upstream parameters. One forward and one reverse pass replace separate full loss recomputations or finite-difference perturbations for every weight.',
 'backprop-sources':'The incoming gradient dL/dy measures loss sensitivity to the output y. With y=wx, the local derivative dy/dw=x measures how y changes when w changes while x stays fixed. The chain rule multiplies these two effects: dL/dw=(dL/dy)x. Its sign indicates which weight direction increases loss; gradient descent subtracts it.',
 'attention-empty':'Query-key dot products are compatibility scores. Softmax converts them to nonnegative weights summing to one. The output is the weighted sum of values; a larger score gives its value more influence, while other values can still contribute. Softmax does not simply select one winner.',
 'attention-sources':'Queries and keys determine dot-product compatibility scores. Softmax normalizes scores into nonnegative weights summing to one. Attention outputs a weighted sum of the value vectors, so higher-weight values contribute more. Divide scores by sqrt(d_k) because dot-product variance grows with key dimension: otherwise large scores saturate softmax and make its gradients very small.',
 'hecke-empty':'In this normalization, Ti squared=(q-1)Ti+q. At q=1 this becomes Ti squared=1, the ordinary permutation relation for repeating a simple swap. The braid relations also remain, recovering permutation group multiplication. Changing q changes the repeated-swap coefficients while retaining the same Coxeter combinatorics.',
 'hecke-sources':'The parameter deforms the quadratic relation to Ti squared=(q-1)Ti+q while the braid relations are retained. Braid relations identify reduced words for each permutation, and the quadratic relation reduces repeated generators. This produces the standard basis Tw indexed by permutations. At q=1 the quadratic relation is Ti squared=1, recovering the group algebra of Sn.',
 'cde-empty':'Reduce a stable R-lattice modulo the maximal ideal. A characteristic-zero irreducible can become reducible or non-semisimple over k. The decomposition map records its class by modular composition factors; that class is independent of the stable lattice chosen. The CDE triangle concerns classes: lift projectives with e, reduce with d, or forget projectivity with c, and c=d composed with e. This does not claim every modular module lifts.',
 'cde-sources':'The map e lifts a kG-projective to a projective lattice over the complete DVR R, then extends to K. Reducing that lifted lattice with d returns the original kG-projective, so its composition factors are unchanged. The direct map c forgets projectivity and records the same class in G0(kG). Thus both routes agree: c=d composed with e.',
 'cohomology-empty':'An oriented edge coboundary is a difference of vertex potentials. Around a closed loop, each intermediate potential cancels with the next, so the total is zero. Therefore an edge assignment with nonzero loop sum cannot come from vertex potentials. Changing potentials adds a coboundary and cannot remove that obstruction.',
 'cohomology-sources':'A cocycle is locally closed: its coboundary on each face is zero. A coboundary is a global gradient of vertex potentials and must telescope to zero around every closed loop. A space with a hole can support a closed edge assignment with nonzero circulation around that hole, so it is not a global gradient. H1 records cocycles modulo coboundaries; filling the hole changes the cocycle condition.',
 'padic-empty':'A field automorphism preserves the valuation ring and its maximal ideal, hence sends integral elements to integral elements and induces a residue-field automorphism by reducing them modulo that ideal. This is a homomorphism from Gal(L/K) onto Gal(l/k) in the stated finite Galois local-field setting. Its kernel consists exactly of automorphisms acting trivially on all residues: inertia I. Therefore G/I is the residue Galois group.',
 'padic-sources':'Reduction sends G=Gal(L/K) onto Gal(l/k). Inertia is the kernel and acts trivially on residues, while G/I describes the unramified part. The two quadratic examples both have abstract group C2 but differ in residue action and ramification: Q5(sqrt(2)) has e=1,f=2 and trivial inertia; Q5(sqrt(5)) is Eisenstein with e=2,f=1 and inertia all of G. The valuation filtration and residue action distinguish them, not group order alone.',
 'riesz-empty':'If T(v)=1 and n lies in ker T, then T(v+t n)=1 for every t, so the entire line remains in the same affine slice. Minimality of the norm at t=0 forces the linear term in norm(v+t n) squared to vanish. Hence the inner product of v with n is zero. In the complex case vary with both n and i n. Thus v is orthogonal to the kernel.',
 'riesz-sources':'The representing vector for f(x,y)=x+2y is (1,2) under the usual real inner product. If two vectors represent the same functional, their difference has inner product zero with every u. Choose u equal to that difference; its squared norm is zero, so the vectors coincide. The general theorem requires a Hilbert space, including completeness, and a bounded linear functional.'
};
let app:ElectronApplication|undefined;const report:any[]=[];const errors:string[]=[];const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(test:()=>Promise<boolean>,message:string,timeout=45000){const end=Date.now()+timeout;while(!await test()){assert(Date.now()<end,message);await sleep(80);}}
try{
 const env=Object.fromEntries(Object.entries({...process.env,STUDIO_DATA_DIR:manifest.data}).filter((e):e is [string,string]=>typeof e[1]==='string'&&e[0]!=='ELECTRON_RUN_AS_NODE'));
 app=await electron.launch({executablePath:resolve('node_modules/electron/dist/electron'),args:['.','--no-sandbox','--ozone-platform=x11'],env});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.locator('.app').waitFor();await page.evaluate(()=>window.studio.call('refreshAccounts'));const state=await page.evaluate(()=>window.studio.call<PublicState>('state'));assert.equal(state.settings.judge,'opencode');assert.equal(state.settings.judgeModel,'jev-1.13-free');
 for(const c of manifest.cases){
  const result:any={id:c.id,judge:'jev-1.13-free'};report.push(result);
  try{assert(c.canvasId,c.id+' must have a published lesson');await page.evaluate(id=>window.studio.call('selectChat',{id}),c.chatId);await page.locator(`iframe[src^="studio://canvas/${c.canvasId}?"]`).waitFor();let frame:Frame|undefined;await until(async()=>{frame=page.frames().find(f=>f.url().startsWith('studio://canvas/'+c.canvasId+'?'));return !!frame;},'Published lesson frame must finish navigation');const readyFrame=frame!;const canvas=await page.evaluate(id=>window.studio.call<Canvas>('getCanvas',{id}),c.canvasId);result.rubric=canvas.rubric;const input=readyFrame.locator('textarea').first();await input.waitFor();assert(await input.count(),'A conceptual written question must be visible');
   await readyFrame.evaluate(()=>{const studio=(window as any).Studio,original=studio.check.bind(studio);(window as any).__quizChecks=[];studio.check=async(answer:any)=>{const call:any={answer,start:performance.now(),pending:true};(window as any).__quizChecks.push(call);try{call.result=await original(answer);return call.result;}catch(e){call.error=String(e);throw e;}finally{call.ms=performance.now()-call.start;call.pending=false;}};});
   const topic=c.id.replace(/-(?:empty|sources)$/,'');const sourceAnswer=answers[topic],answer=sourceAnswer?{...sourceAnswer,correct:focused[c.id]||sourceAnswer.correct}:undefined;assert(answer,'A human-audited test answer is required');
   async function submit(value:string){const before=await readyFrame.evaluate(()=>(window as any).__quizChecks.length);const edited=Date.now();await input.fill(value);await until(()=>readyFrame.evaluate(before=>{const calls=(window as any).__quizChecks;return calls.length>before&&!calls.at(-1).pending;},before),'Actual live feedback must complete after editing');const call=await readyFrame.evaluate(()=>(window as any).__quizChecks.at(-1));assert(!call.error,call.error);call.visibleFeedbackMs=Date.now()-edited;return call;}
   result.wrong=await submit(answer.wrong);assert(result.wrong.result.items.some((x:any)=>x.status!=='demonstrated'),'A misconception must not pass every idea');result.correct=await submit(answer.correct);assert(result.correct.result.items.some((x:any)=>x.status==='demonstrated'),'A correct explanation must demonstrate an idea');result.correctComplete=result.correct.result.items.every((x:any)=>x.status==='demonstrated');
   const before=await readyFrame.evaluate(()=>(window as any).__quizChecks.length);await input.fill(answer.wrong+' I want to revisit this attempt.');await until(()=>readyFrame.evaluate(before=>(window as any).__quizChecks.length>before,before),'A real old request must begin before editing');await input.fill(answer.correct);await until(()=>readyFrame.evaluate(before=>{const calls=(window as any).__quizChecks;return calls.length>=before+2&&!calls.at(-1).pending;},before),'The new answer should be scored');const calls=await readyFrame.evaluate(before=>(window as any).__quizChecks.slice(before),before);result.editCalls=calls;assert(calls.at(-1).result?.items.some((x:any)=>x.status==='demonstrated'));assert.equal(await input.inputValue(),answer.correct);await sleep(1000);result.feedback=await readyFrame.locator('body').innerText();assert(!/confidence\s*[:=]\s*\d|\d+(?:\.\d+)?%\s*(?:confidence|score)/i.test(result.feedback),'Feedback must not expose false precision');
   const detail=readyFrame.getByRole('button',{name:/detailed|feedback from|ask.*feedback|ask Loom/i}).first();if(await detail.count()){await detail.click();await until(async()=> (await page.getByRole('textbox',{name:'Message',exact:true}).inputValue()).includes(answer.correct),'Detailed question must reach the composer');const draft=await page.getByRole('textbox',{name:'Message',exact:true}).inputValue();assert(draft.includes(answer.correct),'Detailed feedback must include the actual learner answer');assert(draft.length>answer.correct.length,'Detailed feedback must include question/context');result.detailedDraft=draft.slice(0,6000);
    if(['backprop-sources','riesz-sources'].includes(c.id)){
      const chosen=(await page.evaluate(()=>window.studio.call<PublicState>('state'))).chats.find(x=>x.id===c.chatId)!;assert.equal(chosen.model,'gpt-6-luna');assert.equal(chosen.thinking,'low');
      const measure=async(text?:string)=>{if(text)await page.getByRole('textbox',{name:'Message',exact:true}).fill(text);const start=Date.now();let firstTextMs:number|undefined;const before=(await page.evaluate(()=>window.studio.call<PublicState>('state'))).chats.find(x=>x.id===c.chatId)!.messages.length;await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await until(async()=>{const s=await page.evaluate(()=>window.studio.call<PublicState>('state')),run=s.runs.find(x=>x.chatId===c.chatId),chat=s.chats.find(x=>x.id===c.chatId)!;if(firstTextMs===undefined&&(run?.text.trim()||chat.messages.slice(before).some(m=>m.role==='assistant'&&m.text.trim())))firstTextMs=Date.now()-start;return chat.messages.length>before&&!!run&&!run.busy;},'Luna Low detailed feedback must finish',120000);const s=await page.evaluate(()=>window.studio.call<PublicState>('state'));assert.equal(s.runs.find(x=>x.chatId===c.chatId)?.error,undefined);const reply=s.chats.find(x=>x.id===c.chatId)!.messages.slice(before).filter(m=>m.role==='assistant').map(m=>m.text).join(' ');assert(reply.trim().length>30);return{firstTextMs,completeMs:Date.now()-start,reply};};
      result.detailedLuna=await measure();result.followupLuna=await measure('Give me one short transfer question that checks the same idea in a different example.');
    }
}
   result.rendererMathErrors=await readyFrame.locator('.katex-error').count();assert.equal(result.rendererMathErrors,0);result.pass=true;console.log('QUIZ',JSON.stringify({id:c.id,wrong:result.wrong.result.items.map((x:any)=>x.status),correct:result.correct.result.items.map((x:any)=>x.status),wrongMs:Math.round(result.wrong.ms),correctMs:Math.round(result.correct.ms)}));
  }catch(e){result.error=e instanceof Error?e.message:String(e);console.log('FAIL',c.id,result.error);}await writeFile(join(root,'quiz-report.json'),JSON.stringify({report,errors},null,2));
 }
 assert.deepEqual(errors,[]);assert.deepEqual(report.filter(r=>r.error).map(r=>({id:r.id,error:r.error})),[],'Every generated lesson must support working live feedback');
}finally{await app?.close();}
