import {_electron as electron,type ElectronApplication} from 'playwright-core';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../src/store.ts';
import type {PublicState} from '../src/shared.ts';
const data=await mkdtemp(join(tmpdir(),'loom-thinking-e2e-')),log=join(data,'wire.jsonl');
const bin=join(data,'runtime/node_modules/@openai/codex/bin');await mkdir(bin,{recursive:true});await writeFile(join(data,'runtime/.ready'),'fixture');
await writeFile(join(bin,'codex.js'),`const fs=require('node:fs'),rl=require('node:readline');const out=p=>process.stdout.write(JSON.stringify(p)+'\\n');rl.createInterface({input:process.stdin}).on('line',line=>{const p=JSON.parse(line);fs.appendFileSync(${JSON.stringify(log)},line+'\\n');if(!p.method||p.method==='initialized')return;let result={};if(p.method==='account/read')result={account:{type:'chatgpt'}};if(p.method==='model/list')result=p.params.cursor?{data:[{id:'unknown',model:'unknown',displayName:'Unknown capabilities'}],nextCursor:null}:{data:[{id:'a',model:'a',displayName:'Model A',defaultReasoningEffort:'high',supportedReasoningEfforts:[{reasoningEffort:'low',description:'Fast'},{reasoningEffort:'high',description:'Deep'}]},{id:'b',model:'b',displayName:'Model B',defaultReasoningEffort:'ultra',supportedReasoningEfforts:[{reasoningEffort:'none'},{reasoningEffort:'ultra'}]}],nextCursor:'page2'};if(p.method==='thread/start')result={thread:{id:'thread'}};if(p.method==='turn/start'){result={turn:{id:'turn'}};setTimeout(()=>out({method:'turn/completed',params:{threadId:'thread',turn:{id:'turn',status:'completed'}}}),500);}out({id:p.id,result});});`);
const store=new Store(data);await store.init();const chat=await store.newChat({provider:'openai-codex',model:'a'});await store.commit();let app:ElectronApplication|undefined;const errors:string[]=[],checks:string[]=[];
const env=Object.fromEntries(Object.entries({...process.env,STUDIO_DATA_DIR:data}).filter((e):e is [string,string]=>typeof e[1]==='string'&&e[0]!=='ELECTRON_RUN_AS_NODE'));
try{
  app=await electron.launch({executablePath:resolve('node_modules/electron/dist/electron'),args:['.','--no-sandbox','--ozone-platform=x11'],env});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.locator('.app').waitFor();await page.evaluate(()=>window.studio.call('refreshAccounts'));
  const dial=page.getByRole('combobox',{name:'Thinking level',exact:true}),model=page.getByRole('combobox',{name:'Chat model',exact:true});await dial.locator('option[value="low"]').waitFor({state:'attached'});assert.deepEqual(await dial.locator('option').evaluateAll(options=>options.map(x=>(x as HTMLOptionElement).value)),['','low','high']);assert.match(await dial.locator('option[value=""]').innerText(),/High/);
  await dial.selectOption('low');await page.getByRole('textbox',{name:'Message',exact:true}).fill('A simple test');await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await page.getByRole('button',{name:'Stop',exact:true}).waitFor({state:'attached'});assert(await dial.isDisabled());await page.getByRole('button',{name:'Send',exact:true}).waitFor();const packets=(await readFile(log,'utf8')).trim().split('\n').map(x=>JSON.parse(x));assert.equal(packets.find(x=>x.method==='turn/start').params.effort,'low');checks.push('Provider catalog choices, defaults, pagination, Low on the wire, and disabled changes during a response');
  await model.selectOption('b');await dial.locator('option[value="ultra"]').waitFor({state:'attached'});assert.deepEqual(await dial.locator('option').evaluateAll(options=>options.map(x=>(x as HTMLOptionElement).value)),['','none','ultra']);assert.equal(await dial.inputValue(),'');await dial.selectOption('ultra');await model.selectOption('a');await dial.locator('option[value="low"]').waitFor({state:'attached'});assert.equal(await dial.inputValue(),'low');await model.selectOption('unknown');await page.waitForFunction(()=>document.querySelector<HTMLSelectElement>('[aria-label="Thinking level"]')?.disabled);assert(await dial.isDisabled());assert.equal(await dial.inputValue(),'');checks.push('Different and future level sets, per-model preferences, and honest unknown capabilities');
  await model.selectOption('a');await dial.locator('option[value="low"]').waitFor({state:'attached'});for(const theme of ['light','dark']){await page.evaluate(theme=>window.studio.call('settings',{theme}),theme);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(740,700));await page.waitForTimeout(100);assert(await dial.isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await dial.evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth}));}checks.push('Readable selector stays inside the minimum-width window in light and dark');
  await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/thinking-controls.png'});await app.close();app=undefined;const restored=new Store(data);await restored.init();assert.equal(restored.chat(chat.id).thinking,'low');assert.deepEqual(errors,[]);await writeFile('test-results/thinking-report.json',JSON.stringify({checks,errors,fixture:'Deterministic provider catalog; no paid calls'},null,2));console.log(JSON.stringify({checks,errors}));
}finally{await app?.close();await rm(data,{recursive:true,force:true});}
