import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import DOMPurify from 'dompurify';
import {Menu,Plus,Settings,Paperclip,ArrowUp,Square,X,ArrowLeft,Folder,RefreshCw,ScanLine,BookOpen} from 'lucide-react';
import {renderMarkdown} from '../../src/markdown.ts';
import {readingSize} from '../../src/canvas-theme.ts';
import {SAMPLE_HTML} from '../../src/sample.ts';
import type {Canvas,CanvasPreview,PublicState,Attachment} from '../../src/shared.ts';
import {native,rpc,onNative} from './native.ts';
import {documentFor,previewFor} from './documents.ts';
import './style.css';

type PendingCanvas={state?:unknown;quizAnswers?:Record<string,string>};
type Cache={state?:PublicState;documents:Record<string,Canvas>;outbox?:Record<string,PendingCanvas>};
const message=(e:unknown)=>e instanceof Error?e.message:String(e);
const localId='local-signal';
const documents:Record<string,Canvas>={};
const outbox:Record<string,PendingCanvas>={};
const syncing=new Map<string,Promise<void>>();
let cached:PublicState|undefined;
let cacheTimer:ReturnType<typeof setTimeout>;
function cache(state?:PublicState){if(state)cached={...state,runs:[]};clearTimeout(cacheTimer);cacheTimer=setTimeout(()=>{const entries=Object.entries(documents).sort((a,b)=>b[1].updatedAt-a[1].updatedAt);const kept:Record<string,Canvas>={};let bytes=0;for(const[id,c]of entries){bytes+=JSON.stringify(c).length;if(bytes>8*1024*1024)break;kept[id]={...c,versions:[]};}void native('saveCache',{state:cached,documents:kept,outbox}).catch(()=>{});},400);}
function syncCanvas(id:string):Promise<void>{const prior=syncing.get(id);if(prior)return prior;const job=(async()=>{while(outbox[id]){const saved=outbox[id];if(Object.hasOwn(saved,'state'))await rpc('canvasState',{id,state:saved.state});for(const[key,answer]of Object.entries(saved.quizAnswers||{}))await rpc('canvasQuizAnswer',{id,key,answer});if(outbox[id]===saved){delete outbox[id];cache();}}})().finally(()=>syncing.delete(id));syncing.set(id,job);return job;}
function queueCanvas(id:string,value:PendingCanvas){if(id===localId)return;outbox[id]={...outbox[id],...value,quizAnswers:{...outbox[id]?.quizAnswers,...value.quizAnswers}};cache();}
function Button({label,children,onClick,disabled}:{label:string;children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button className="icon" aria-label={label} title={label} onClick={onClick} disabled={disabled}>{children}</button>;}
function Text({text,source}:{text:string;source:(value:any)=>void}){const html=useMemo(()=>renderMarkdown(text,value=>DOMPurify.sanitize(value,{FORBID_TAGS:['style','iframe','form','input','button'],FORBID_ATTR:['style'],ADD_ATTR:['data-loom-math'],ALLOWED_URI_REGEXP:/^(?:https?:|studio:\/\/source(?:[/?]|$)|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i})),[text]);return <div className="markdown" dangerouslySetInnerHTML={{__html:html}} onClick={e=>{const a=(e.target as HTMLElement).closest('a');if(!a)return;e.preventDefault();if(a.href.startsWith('studio://source')){const u=new URL(a.href);source({path:u.searchParams.get('path'),id:u.searchParams.get('id'),page:Number(u.searchParams.get('page'))||1});}else if(/^https?:/.test(a.href))void native('openExternal',{url:a.href}).catch(()=>{});}}/>;}
function LocalFrame({html,token,...props}:{html:string;token:string}&React.ComponentProps<'iframe'>){const[url,setURL]=useState(''),[error,setError]=useState('');useEffect(()=>{let active=true;void native<string>('renderDocument',{id:token,html}).then(url=>{if(active)setURL(url);}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;void native('releaseDocument',{id:token}).catch(()=>{});};},[html,token]);return error?<p className="error">{error}</p>:url?<iframe {...props} src={url}/>:<p className="muted">Opening lesson…</p>;}
function Lesson({meta,appearance,online,ask,source}:{meta:Canvas;appearance:any;online:boolean;ask:(text:string)=>void;source:(value:any)=>void}){
 const [canvas,setCanvas]=useState<Canvas|undefined>(documents[meta.id]),[height,setHeight]=useState(100),[error,setError]=useState('');
 const frame=useRef<HTMLIFrameElement>(null),current=useRef(canvas);current.current=canvas;
 const token=useMemo(()=>crypto.randomUUID(),[meta.id,meta.revision]);
 useEffect(()=>{let active=true;setCanvas(documents[meta.id]);if(online&&meta.id!==localId)void syncCanvas(meta.id).then(()=>rpc<Canvas>('getCanvas',{id:meta.id})).then(next=>{if(active){documents[next.id]=next;setCanvas(next);setError('');cache();}}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[meta.id,meta.revision,online]);
 const html=useMemo(()=>canvas?documentFor(canvas,token,appearance):'', [canvas?.html,canvas?.revision,token]);
 const apply=()=>frame.current?.contentWindow?.postMessage({channel:'studio-canvas',token,type:'appearance',theme:appearance.theme,fontSize:readingSize(appearance.fontSize)},'*');
 useEffect(apply,[appearance.theme,appearance.fontSize,token]);
 useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const listener=async(event:MessageEvent)=>{
  const d=event.data,target=frame.current?.contentWindow;if(event.source!==target||d?.channel!=='studio-canvas'||d.token!==token)return;
  const reply=(result?:unknown,error?:string)=>target?.postMessage({channel:'studio-canvas',token,id:d.id,result,error},'*');
  if(d.type==='resize'&&Number.isFinite(d.height))setHeight(Math.max(80,Math.min(100000,Math.ceil(d.height))));
  if(d.type==='error')setError(String(d.message).slice(0,500));
  if(d.type==='state'&&current.current){current.current.state=d.state;documents[meta.id]=current.current;queueCanvas(meta.id,{state:d.state});cache();clearTimeout(timer);if(online&&meta.id!==localId)timer=setTimeout(()=>void syncCanvas(meta.id).catch(()=>{}),220);}
  if(d.type==='quizAnswer'&&current.current&&typeof d.key==='string'&&typeof d.answer==='string'){current.current.quizAnswers={...current.current.quizAnswers,[d.key]:d.answer};documents[meta.id]=current.current;queueCanvas(meta.id,{quizAnswers:{[d.key]:d.answer}});cache();if(online&&meta.id!==localId)void syncCanvas(meta.id).catch(e=>setError(message(e)));}
  if(d.type==='grade'){if(!online||meta.id===localId){reply(undefined,'Your answer is saved. Connect to desktop Loom for Jev feedback.');return;}try{reply(await rpc('grade',{id:meta.id,answer:d.answer}));}catch(e){reply(undefined,message(e));}}
  if(d.type==='cancelGrade'&&online&&meta.id!==localId)void rpc('cancelGrade',{id:meta.id}).catch(()=>{});
  if(d.type==='ask'&&typeof d.text==='string')ask(d.text.slice(0,10000));
  if(d.type==='source')source(d.source);
  if(d.type==='link'&&typeof d.url==='string'&&/^https?:/.test(d.url)&&confirm('Open this source in your browser?\n'+d.url))void native('openExternal',{url:d.url}).catch(e=>setError(message(e)));
 };window.addEventListener('message',listener);return()=>{window.removeEventListener('message',listener);clearTimeout(timer);};},[token,online]);
 return <section className="lesson" aria-label={meta.title}><div className="lesson-title">{meta.title}</div>{html?<LocalFrame html={html} token={token} ref={frame} title={meta.title} sandbox="allow-scripts" referrerPolicy="no-referrer" style={{height}} onLoad={apply}/>:<p>{online?'Loading lesson…':'This lesson has not been cached. Connect to desktop Loom to open it.'}</p>}{error&&<p className="error">{error}</p>}</section>;
}
function Building({preview,appearance}:{preview:CanvasPreview;appearance:any}){
 const frame=useRef<HTMLIFrameElement>(null),[height,setHeight]=useState(80),token=useMemo(()=>crypto.randomUUID(),[preview.id]);
 const html=useMemo(()=>previewFor(token,appearance),[token]);
 const update=()=>{const target=frame.current?.contentWindow;target?.postMessage({channel:'loom-preview',token,type:'appearance',theme:appearance.theme,fontSize:readingSize(appearance.fontSize)},'*');target?.postMessage({channel:'loom-preview',token,type:'html',html:preview.html},'*');};
 useEffect(update,[preview.html,appearance.theme,appearance.fontSize]);
 useEffect(()=>{const listener=(event:MessageEvent)=>{const d=event.data;if(event.source===frame.current?.contentWindow&&d?.channel==='loom-preview'&&d.token===token&&d.type==='resize'&&Number.isFinite(d.height))setHeight(Math.max(80,Math.min(100000,Math.ceil(d.height))));};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener);},[token]);
 return <section className="lesson" aria-busy="true"><div className="lesson-title">{preview.title} · building</div><LocalFrame html={html} token={token} ref={frame} title={preview.title+' preview'} sandbox="allow-scripts" referrerPolicy="no-referrer" style={{height}} onLoad={update}/></section>;
}
function App(){
 const [state,setState]=useState<PublicState>(),[online,setOnline]=useState(false),[paired,setPaired]=useState(false),[url,setURL]=useState(''),[error,setError]=useState(''),[draft,setDraft]=useState(''),[panel,setPanel]=useState<''|'chats'|'settings'|'pair'|'library'|'source'>(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[previews,setPreviews]=useState<Record<string,CanvasPreview>>({}),[files,setFiles]=useState<any[]>([]),[path,setPath]=useState(''),[source,setSource]=useState<any>(),[page,setPage]=useState(1),[limit,setLimit]=useState(40),[systemDark,setSystemDark]=useState(false);
 const snapshot=useRef(state),input=useRef<HTMLTextAreaElement>(null),scroller=useRef<HTMLDivElement>(null),nearBottom=useRef(true),draftTimer=useRef<ReturnType<typeof setTimeout>>(undefined);snapshot.current=state;
 const chat=state?.chats.find(c=>c.id===state.activeChatId),run=state?.runs.find(r=>r.chatId===chat?.id),provider=state?.providers.find(p=>p.id===chat?.provider),model=provider?.models.find(m=>m.id===chat?.model)||provider?.models[0],settings=state?.settings||{theme:'system',fontSize:18},appearance={...settings,theme:settings.theme==='system'?(systemDark?'dark':'light'):settings.theme};
 const accept=(next:PublicState)=>{setState(next);cache(next);};
 const refresh=async()=>{const next=await rpc<PublicState>('state');accept(next);setOnline(true);return next;};
 const action=async(method:string,data:any={})=>{try{const result=await rpc(method,data);await refresh();return result;}catch(e){setError(message(e));throw e;}};
 const quiet=(method:string,data:any={})=>void action(method,data).catch(()=>{});
 useEffect(()=>{
  void native<Cache|null>('loadCache').then(value=>{if(value){Object.assign(documents,value.documents);Object.assign(outbox,value.outbox);if(value.state&&!snapshot.current)accept(value.state);}}).catch(()=>{});
  void native('status').then(status=>{setPaired(status.paired);setURL(status.url);setSystemDark(status.systemDark);if(status.paired){void refresh().catch(e=>setError(message(e)));void native('startEvents');}}).catch(e=>setError(message(e)));
  void native<string>('launchCode').then(value=>{if(value){setCode(value);setPanel('pair');}}).catch(()=>{});
  let frame=0;const deltas=new Map<string,string>();
  const stop=onNative(event=>{
   if(event.type==='state'){cancelAnimationFrame(frame);frame=0;deltas.clear();accept(event.state);}
   if(event.type==='connection'){setOnline(event.online);if(event.online)setError('');else if(event.error)setError(event.error);}
   if(event.type==='pair-code'){setCode(event.code);setPanel('pair');}
   if(event.type==='system-theme')setSystemDark(event.dark);
   if(event.type==='delta'){deltas.set(event.chatId,(deltas.get(event.chatId)||'')+event.delta);if(!frame)frame=requestAnimationFrame(()=>{frame=0;const pending=new Map(deltas);deltas.clear();setState(current=>current?{...current,runs:current.runs.map(r=>pending.has(r.chatId)?{...r,text:r.text+pending.get(r.chatId)}:r)}:current);});}
   if(event.type==='canvas-preview')setPreviews(current=>{const next={...current};if(event.preview)next[event.chatId]=event.preview;else delete next[event.chatId];return next;});
  });return()=>{stop();cancelAnimationFrame(frame);};
 },[]);
 useEffect(()=>{setDraft(chat?.draft||'');setLimit(40);nearBottom.current=true;},[chat?.id]);
 useEffect(()=>{document.documentElement.dataset.theme=appearance.theme;document.documentElement.style.setProperty('--reading-size',readingSize(appearance.fontSize)+'px');void native('appearance',{theme:settings.theme}).catch(()=>{});},[appearance.theme,appearance.fontSize,settings.theme]);
 useEffect(()=>{const n=input.current;if(n){n.style.height='auto';n.style.height=Math.min(160,n.scrollHeight)+'px';}},[draft]);
 useEffect(()=>{if(nearBottom.current)requestAnimationFrame(()=>scroller.current?.scrollTo(0,scroller.current.scrollHeight));},[chat?.messages.length,run?.text,previews]);
 useEffect(()=>{const back=()=>{if(panel)setPanel('');else void native('background');};window.addEventListener('loom-back',back);return()=>window.removeEventListener('loom-back',back);},[panel]);
 useEffect(()=>{if(!panel)return;const prior=document.activeElement as HTMLElement;requestAnimationFrame(()=>document.querySelector<HTMLElement>('.sheet button')?.focus());const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setPanel('');}if(event.key==='Tab'){const nodes=[...document.querySelectorAll<HTMLElement>('.sheet button:not(:disabled),.sheet input,.sheet textarea,.sheet select')].filter(n=>n.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}};document.addEventListener('keydown',keyboard);return()=>{document.removeEventListener('keydown',keyboard);prior?.focus();};},[panel]);
 const updateDraft=(value:string)=>{setDraft(value);if(chat){chat.draft=value;cache(snapshot.current);clearTimeout(draftTimer.current);if(online&&chat.id!==localId)draftTimer.current=setTimeout(()=>void rpc('saveDraft',{chatId:chat.id,text:value}).catch(()=>{}),250);}};
 const ask=(text:string)=>{updateDraft(text);input.current?.focus();};
 const send=async()=>{if(!chat||busy||!online||(!draft.trim()&&!chat.draftAttachments.length))return;setBusy(true);setError('');clearTimeout(draftTimer.current);try{await rpc('saveDraft',{chatId:chat.id,text:draft});await rpc('send',{chatId:chat.id,text:draft,attachments:chat.draftAttachments});setDraft('');await refresh();nearBottom.current=true;}catch(e){setError(message(e));}finally{setBusy(false);}};
 const pair=async(value=code)=>{setBusy(true);setError('');try{const status=await native('pair',{code:value});setPaired(true);setURL(status.url);await refresh();await native('startEvents');setCode('');setPanel('');}catch(e){setError(message(e));}finally{setBusy(false);}};
 const openSample=()=>{const canvas:Canvas={id:localId,chatId:localId,title:'Sine wave',html:SAMPLE_HTML,revision:1,versions:[],state:documents[localId]?.state||{},rubric:[],updatedAt:Date.now()};documents[localId]=canvas;const base:PublicState=state||{version:1,chats:[],projects:[],folders:[],canvases:[],attachments:[],settings:{provider:'openai-codex',models:{},judge:'opencode',judgeModel:'jev-1.13-free',theme:'system',fontSize:18,customPrompt:''},providers:[],judges:[],runs:[]};accept({...base,activeChatId:localId,chats:[...base.chats.filter(c=>c.id!==localId),{id:localId,title:'Signal lab · offline sample',provider:'openai-codex',model:'',messages:[{id:localId,role:'assistant',text:'Change the signal. Predict what happens, then test your prediction.',at:Date.now(),canvasIds:[localId]}],draft:'',draftAttachments:[],updatedAt:Date.now()}],canvases:[...base.canvases.filter(c=>c.id!==localId),canvas]});setPanel('');};
 const sourcePDF=async(value:any,p=1)=>{setPanel('source');setSource({loading:true});setPage(p);try{const result=await rpc('pdfPreview',{chatId:chat?.id,...value,page:p});setSource({value,result});}catch(e){setSource({text:message(e)});}};
 const attachPreview=async(item:Attachment)=>{if(item.mime==='application/pdf'){void sourcePDF({id:item.id});return;}setPanel('source');setSource({loading:true});try{const value=await rpc('mobileAttachment',{id:item.id});setSource(item.mime.startsWith('image/')&&item.mime!=='image/svg+xml'?{image:'data:'+item.mime+';base64,'+value.bytes,name:item.name}:{text:atob(value.bytes),name:item.name});}catch(e){setSource({text:message(e)});}};
 const listFiles=async(target='')=>{setPanel('library');setPath(target);try{setFiles(await rpc('listFiles',{chatId:chat?.id,path:target}));}catch(e){setError(message(e));}};
 const createProject=async()=>{const name=prompt('Project name');if(!name)return;try{const project=await action('mobileCreateProject',{name});await action('newChat',{projectId:project.id});setPanel('');}catch{}};
 const attachments=(ids:string[])=>state?.attachments.filter(a=>ids.includes(a.id))||[];
 const upload=async()=>{if(!chat)return;setBusy(true);try{const result=await native('pickFiles',{chatId:chat.id});if(result?.error)setError(result.error);await refresh();}catch(e){setError(message(e));}finally{setBusy(false);}};
 return <div className="app"><div className="workspace" inert={!!panel}>
  <header><Button label="Chats" onClick={()=>setPanel('chats')}><Menu size={20}/></Button><img src="logo.svg" alt=""/><strong>{chat?.title||'Loom'}</strong><button className="connection" onClick={()=>setPanel('pair')} aria-label={online?'Desktop connected':'Connect desktop'}><span data-online={online}/>{online?'Connected':paired?'Offline':'Connect'}</button><Button label="Settings" onClick={()=>setPanel('settings')}><Settings size={19}/></Button></header>
  {chat&&chat.id!==localId&&<div className="model-bar"><select aria-label="Provider" value={chat.provider} disabled={!online||run?.busy} onChange={e=>quiet('updateChat',{id:chat.id,provider:e.target.value})}>{state?.providers.map(p=><option value={p.id} key={p.id} disabled={!p.available}>{p.name}</option>)}</select><select aria-label="Model" value={chat.model||model?.id||''} disabled={!online||run?.busy} onChange={e=>quiet('updateChat',{id:chat.id,model:e.target.value})}>{provider?.models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>{!!model?.thinking?.length&&<select aria-label="Thinking" value={chat.thinking||model.defaultThinking||''} disabled={!online||run?.busy} onChange={e=>quiet('updateChat',{id:chat.id,thinking:e.target.value})}><option value="">Default thinking</option>{model.thinking.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select>}{!!model?.speeds?.length&&model.speeds.length>1&&<select aria-label="Speed" value={chat.speed||"standard"} disabled={!online||run?.busy} onChange={e=>quiet("updateChat",{id:chat.id,speed:e.target.value})}>{model.speeds.map(speed=><option key={speed} value={speed}>{speed[0].toUpperCase()+speed.slice(1)}</option>)}</select>}</div>}
  <main ref={scroller} onScroll={e=>{const n=e.currentTarget;nearBottom.current=n.scrollHeight-n.scrollTop-n.clientHeight<100;}}>
   {!chat&&<div className="welcome"><h1>Loom</h1><p>Interactive lessons, source papers, and feedback.</p><button onClick={()=>setPanel('pair')}>Connect desktop</button><button onClick={openSample}>Open local sample</button><p className="muted">Lessons render on your phone. Your desktop supplies model responses and Jev checks.</p></div>}
   {!!chat&&chat.messages.length>limit&&<button onClick={()=>setLimit(n=>n+40)}>Load earlier messages</button>}
   {chat?.messages.slice(-limit).map(m=><article key={m.id} className={'message '+m.role}><div className="role">{m.role==='user'?'You':'Loom'}{m.steering?' · steering':''}</div><Text text={m.text} source={sourcePDF}/>{!!m.attachments?.length&&<div className="attachments">{attachments(m.attachments).map(a=><button key={a.id} onClick={()=>void attachPreview(a)}>{a.name}</button>)}</div>}{m.canvasIds?.map(id=>{const canvas=state?.canvases.find(c=>c.id===id);return canvas?<Lesson key={id} meta={canvas} appearance={appearance} online={online} ask={ask} source={sourcePDF}/>:null;})}</article>)}
   {run?.busy&&<article className="message assistant"><div className="role">Loom · {run.activity||'Working'}{run.pendingSteers?' · '+run.pendingSteers+' steer queued':''}</div><Text text={run.text} source={sourcePDF}/>{chat&&previews[chat.id]&&<Building preview={previews[chat.id]} appearance={appearance}/>}</article>}
   {run?.error&&<div className="error">{run.error}{run.canRetry&&<button disabled={!online||busy} onClick={()=>quiet('retry',{chatId:chat?.id})}>Retry</button>}</div>}
  </main>
  {error&&<div className="banner" role="status"><span>{error}</span><Button label="Dismiss" onClick={()=>setError('')}><X size={16}/></Button></div>}
  {chat&&<footer><div className="attachments">{attachments(chat.draftAttachments).map(a=><span key={a.id}><button onClick={()=>void attachPreview(a)}>{a.name}</button><button aria-label={'Remove '+a.name} disabled={!online} onClick={()=>quiet('removeAttachment',{chatId:chat.id,id:a.id})}>×</button></span>)}</div><div className="composer"><Button label="Attach files" onClick={()=>void upload()} disabled={!online||busy}><Paperclip size={20}/></Button><textarea ref={input} aria-label="Message" rows={1} value={draft} placeholder={run?.busy?'Steer the lesson…':online?'Message Loom…':'Connect desktop to send'} onChange={e=>updateDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/>{run?.busy&&<Button label="Stop" onClick={()=>quiet('stop',{chatId:chat.id})}><Square size={16}/></Button>}<Button label={run?.busy?'Steer':'Send'} onClick={()=>void send()} disabled={!online||busy||(!draft.trim()&&!chat.draftAttachments.length)}><ArrowUp size={22}/></Button></div></footer>}
  </div>{!!panel&&<div className="sheet" role="dialog" aria-modal="true" aria-label={panel}><div className="sheet-heading"><Button label="Back" onClick={()=>setPanel('')}><ArrowLeft size={20}/></Button><strong>{{chats:'Chats',settings:'Settings',pair:'Connect desktop',library:'Project files',source:source?.name||'Source'}[panel]}</strong></div>
   {panel==='pair'&&<div className="form"><p>On your computer, open Loom → Settings → Phone and enable phone access. Keep both devices on the same Wi-Fi or a private VPN.</p><button disabled={busy} onClick={()=>void native<string>('scanPair').then(value=>{if(value)setCode(value);}).catch(e=>setError(message(e)))}><ScanLine size={18}/>Scan QR code</button><label>Pairing code<textarea value={code} onChange={e=>setCode(e.target.value)} placeholder="loom://pair?code=…" autoCapitalize="none" spellCheck={false}/></label><button disabled={busy||!code.trim()} onClick={()=>void pair()}>{busy?'Connecting…':'Connect'}</button>{paired&&<><p className="muted">{url}</p><button disabled={busy} onClick={()=>void native('startEvents').then(()=>refresh()).then(()=>setPanel('')).catch(e=>setError(message(e)))}>Reconnect</button><button onClick={()=>void native('disconnect').then(()=>{setOnline(false);setPaired(false);setURL('');setState(undefined);cached=undefined;clearTimeout(cacheTimer);for(const id of Object.keys(documents))delete documents[id];for(const id of Object.keys(outbox))delete outbox[id];setPanel('');})}>Forget desktop and cached lessons</button></>}<button onClick={openSample}>Open local sample</button><p className="muted">Provider credentials stay on the computer. The connection is encrypted and pinned to its certificate.</p></div>}
   {panel==='chats'&&<div className="chat-list"><button disabled={!online} onClick={()=>void action('newChat').then(()=>setPanel('')).catch(()=>{})}><Plus size={18}/>New chat</button><button disabled={!online} onClick={()=>void createProject()}><Folder size={18}/>New project</button>{state?.projects.map(p=><section key={p.id}><div className="project-heading"><strong>{p.name}</strong><Button label={'New chat in '+p.name} onClick={()=>void action('newChat',{projectId:p.id}).then(()=>setPanel('')).catch(()=>{})} disabled={!online}><Plus size={17}/></Button></div>{state.chats.filter(c=>c.projectId===p.id).sort((a,b)=>b.updatedAt-a.updatedAt).map(c=><button key={c.id} aria-current={c.id===chat?.id} onClick={()=>{if(online)void action('selectChat',{id:c.id}).then(()=>setPanel('')).catch(()=>{});else{accept({...state,activeChatId:c.id});setPanel('');}}}>{c.title}</button>)}</section>)}<h3>Chats</h3>{state?.chats.filter(c=>!c.projectId).sort((a,b)=>b.updatedAt-a.updatedAt).map(c=><button key={c.id} aria-current={c.id===chat?.id} onClick={()=>{if(online&&c.id!==localId)void action('selectChat',{id:c.id}).then(()=>setPanel('')).catch(()=>{});else{accept({...state,activeChatId:c.id});setPanel('');}}}>{c.title}</button>)}<button onClick={openSample}>Signal lab · local sample</button></div>}
   {panel==='settings'&&<div className="form"><label>Appearance<select aria-label="Appearance" value={settings.theme} onChange={e=>{if(online)quiet('settings',{theme:e.target.value});else if(state)accept({...state,settings:{...state.settings,theme:e.target.value as any}});}}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Text size<select aria-label="Text size" value={readingSize(appearance.fontSize)} onChange={e=>{if(online)quiet('settings',{fontSize:Number(e.target.value)});else if(state)accept({...state,settings:{...state.settings,fontSize:Number(e.target.value)}});}}>{[12,14,16,18,20,22,24].map(n=><option value={n} key={n}>{n} px</option>)}</select></label><p className="muted">Computer Modern · same font in chat and lessons.</p><button onClick={()=>setPanel('pair')}>Desktop connection · {online?'connected':'offline'}</button><button disabled={!online||!chat} onClick={()=>void listFiles()}><BookOpen size={18}/>Project files</button><button disabled={!online} onClick={()=>quiet('refreshAccounts')}><RefreshCw size={17}/>Refresh models</button><p className="muted">Sign in and select Jev on desktop Loom. Phone model and thinking controls use the desktop provider catalog.</p><p className="muted">Loom 0.1.0 · Android 8 or later</p></div>}
   {panel==='library'&&<div className="form"><p>{path||'Project root'}</p>{path&&<button onClick={()=>void listFiles(path.split('/').slice(0,-1).join('/'))}>Parent folder</button>}<button onClick={()=>{const name=prompt('Folder name');if(name)void action('createFolder',{kind:'disk',chatId:chat?.id,name,parent:path}).then(()=>listFiles(path)).catch(()=>{});}}>Create folder</button>{files.map(file=><button key={file.path} onClick={()=>{if(file.directory)void listFiles(file.path);else if(/\.pdf$/i.test(file.name))void sourcePDF({path:file.path});else{setPanel('source');setSource({loading:true,name:file.name});void rpc('readFile',{chatId:chat?.id,path:file.path}).then(text=>setSource({text,name:file.name})).catch(e=>setSource({text:message(e)}));}}}>{file.directory?'▸ ':''}{file.name}</button>)}</div>}
   {panel==='source'&&<div className="source-view">{source?.loading?<p>Loading source…</p>:source?.image?<img src={source.image} alt={source.name}/>:source?.result?<><div className="page-controls"><button disabled={page<=1} onClick={()=>void sourcePDF(source.value,page-1)}>Previous</button><span>Page {page}</span><button onClick={()=>void sourcePDF(source.value,page+1)}>Next</button></div>{source.result.pages?.map((p:any,i:number)=><img key={i} src={p.dataUrl||p.data||p.image} alt={'PDF page '+(p.page||page)}/>)}{!source.result.pages&&<pre>{JSON.stringify(source.result,null,2)}</pre>}</>:<pre>{source?.text}</pre>}</div>}
   {!!error&&<p className="error">{error}</p>}
  </div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
