import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';
import { request as httpsRequest } from 'node:https';
import { Readable } from 'node:stream';
import { mkdir, writeFile } from 'node:fs/promises';
import { join, basename } from 'node:path';
import { scopedPath } from './store.ts';
function publicAddress(address:string){if(address.includes(':'))return !/^(?:\:\:|fc|fd|fe[89ab]|ff|2001:db8)/i.test(address)&&!address.toLowerCase().includes('ffff:');const a=address.split('.').map(Number);return a[0]!==0&&a[0]!==10&&a[0]!==127&&a[0]!==169&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&a[1]===168)&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&a[0]<224;}
export async function publicURL(value:string){const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443')throw Error('Use a public HTTPS paper link.');const hostname=url.hostname.replace(/^\[|\]$/g,'');const addresses=isIP(hostname)?[{address:hostname}]:await lookup(hostname,{all:true});if(!addresses.length||addresses.some(a=>!publicAddress(a.address)))throw Error('This link does not point to a public website.');return url;}
async function request(url:string){let target=url;for(let i=0;i<5;i++){const approved=await publicURL(target);const hostname=approved.hostname.replace(/^\[|\]$/g,'');const addresses=isIP(hostname)?[{address:hostname,family:isIP(hostname)}]:await lookup(hostname,{all:true});if(addresses.some(a=>!publicAddress(a.address)))throw Error('This link does not point to a public website.');
    // Pin the checked DNS result to the TLS request, including each redirect.
    const response=await new Promise<Response>((resolve,reject)=>{const request=httpsRequest(approved,{signal:AbortSignal.timeout(20000),headers:{'User-Agent':'Loom/0.1.0 (interactive study workspace)'},lookup:((_host:any,options:any,callback:any)=>options.all?callback(null,addresses):callback(null,addresses[0].address,addresses[0].family)) as any},r=>{const headers=new Headers();for(const [key,value] of Object.entries(r.headers)){if(value)headers.set(key,Array.isArray(value)?value.join(', '):value);}resolve(new Response(Readable.toWeb(r) as ReadableStream,{status:r.statusCode||500,headers}));});request.on('error',reject);request.end();});
    if([301,302,303,307,308].includes(response.status)){await response.body?.cancel();const location=response.headers.get('location');if(!location)throw Error('The paper server returned an empty redirect.');target=new URL(location,approved).href;continue;}if(!response.ok){await response.body?.cancel();throw Error(`The paper server returned ${response.status}.`);}return{response,url:approved.href};}throw Error('Too many redirects.');}
async function limited(response:Response,max:number){if(Number(response.headers.get('content-length'))>max)throw Error('This download is too large.');if(!response.body)throw Error('The download is empty.');const reader=response.body.getReader(),parts:Uint8Array[]=[];let total=0;try{while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>max)throw Error('This download is too large.');parts.push(value);}}catch(e){await reader.cancel();throw e;}return Buffer.concat(parts);}
const plain=(s:string)=>s.replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
let searchQueue:Promise<unknown>=Promise.resolve(),lastSearch=0;const cache=new Map<string,{at:number;result:any[]}>();
export async function searchPapers(query:string,transport=request){if(typeof query!=='string'||!query.trim()||query.length>300)throw Error('Use a short paper search.');const found=cache.get(query);if(found&&Date.now()-found.at<3600000)return found.result;const task=searchQueue.catch(()=>{}).then(async()=>{const delay=Math.max(0,3000-(Date.now()-lastSearch));if(delay)await new Promise(r=>setTimeout(r,delay));lastSearch=Date.now();const url='https://export.arxiv.org/api/query?'+new URLSearchParams({search_query:query,max_results:'8',sortBy:'relevance'});const {response}=await transport(url);const xml=(await limited(response,1000000)).toString('utf8');const result=[...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(m=>{const read=(tag:string)=>plain(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`).exec(m[1])?.[1]||'');const id=read('id').replace(/^http:/,'https:');return{title:read('title'),abstract:read('summary'),published:read('published'),authors:[...m[1].matchAll(/<name>([\s\S]*?)<\/name>/g)].map(n=>plain(n[1])),url:id,pdfURL:id.replace('/abs/','/pdf/')};});if(cache.size>=100)cache.delete(cache.keys().next().value!);cache.set(query,{at:Date.now(),result});return result;});searchQueue=task;return task;}
export async function downloadPaper(root:string,url:string,name?:string,transport=request){const parsed=new URL(url);if(/^(?:export\.)?arxiv\.org$/.test(parsed.hostname)&&parsed.pathname.startsWith('/abs/'))parsed.pathname=parsed.pathname.replace('/abs/','/pdf/');const result=await transport(parsed.href),bytes=await limited(result.response,100*1024*1024);if(!bytes.subarray(0,1024).includes(Buffer.from('%PDF-')))throw Error('This link did not return a PDF. Choose the paper’s PDF link.');let filename=(name||basename(new URL(result.url).pathname)||'paper').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').slice(0,110);if(!filename.toLowerCase().endsWith('.pdf'))filename+='.pdf';const folder=await scopedPath(root,'papers',true);await mkdir(folder,{recursive:true});const destination=await scopedPath(root,join('papers',filename),true);
  // Exclusive creation prevents a download from replacing an existing textbook.
  await writeFile(destination,bytes,{flag:'wx'});await writeFile(destination+'.source.json',JSON.stringify({url:result.url,requestedURL:url,downloadedAt:new Date().toISOString()},null,2),{flag:'wx'});return{path:'papers/'+filename,sourceURL:result.url,size:bytes.length};}
