import React,{useEffect,useState} from 'react';
import type {PhoneStatus} from './companion.ts';
export function PhonePanel(){
 const [status,setStatus]=useState<PhoneStatus>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[address,setAddress]=useState(0),[copied,setCopied]=useState(false);
 const update=async(method='phoneStatus')=>{setBusy(true);setError('');try{setStatus(await window.studio.call(method));setCopied(false);}catch(e){setError(e instanceof Error?e.message:'The phone connection failed.');}finally{setBusy(false);}};
 useEffect(()=>{void update();},[]);
 const current=status?.addresses[Math.min(address,(status?.addresses.length||1)-1)];
 return <div className="phone-panel"><p>Connect the Android app to this workspace. Both devices need the same Wi-Fi network or a private VPN. Keep desktop Loom running for model responses and live quiz feedback.</p>{!status?.enabled?<button className="primary" disabled={busy||!status} onClick={()=>void update('phoneEnable')}>{busy?'Preparing…':'Enable phone connection'}</button>:<><p>{status.connections?`${status.connections} phone connection${status.connections===1?'':'s'} active`:'Ready to pair'}</p>{status.addresses.length>1&&<label>Computer address<select aria-label="Phone connection address" value={address} onChange={e=>setAddress(Number(e.target.value))}>{status.addresses.map((a,i)=><option key={a.url} value={i}>{a.url}</option>)}</select></label>}{current&&<><img className="phone-qr" src={current.qr} alt="Android pairing QR code"/><p>In the Android app, scan this code or paste the pairing code.</p><button className="small-button" onClick={()=>{void navigator.clipboard.writeText(current.code).then(()=>setCopied(true)).catch(()=>setError('The code could not be copied.'));}}>{copied?'Copied':'Copy pairing code'}</button></>}<p className="muted">Pairing grants access to this library and its model connections. Provider sign-ins stay on this computer.</p><div className="phone-actions"><button disabled={busy} onClick={()=>void update('phoneRevoke')}>Revoke paired phones</button><button disabled={busy} onClick={()=>void update('phoneDisable')}>Disable phone connection</button><button disabled={busy} onClick={()=>void update()}>Refresh</button></div></>}{error&&<p role="alert" className="form-error">{error}<button onClick={()=>void update()}>Retry</button></p>}</div>;
}
